Repository samvera/hyrax, pull requests merged in 2018-04, with the labels that each got.

#2846 Only show viewable images with UniversalViewer
  app/presenters/hyrax/displays_image.rb
  app/presenters/hyrax/work_show_presenter.rb
  spec/presenters/hyrax/file_set_presenter_spec.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
Labels: in progress

#2874 render home breadcrumb with dashboard awareness of user signed in
  app/controllers/concerns/hyrax/breadcrumbs.rb
  app/controllers/hyrax/dashboard_controller.rb
  spec/controllers/hyrax/batch_edits_controller_spec.rb
  spec/controllers/hyrax/citations_controller_spec.rb
  spec/controllers/hyrax/collections_controller_spec.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/controllers/hyrax/file_sets_controller_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/controllers/hyrax/stats_controller_spec.rb
Labels: in progress

#2876 dashboard/collections: only allow 'nest collection' when authed
  app/views/hyrax/dashboard/collections/_show_actions.html.erb
  spec/views/hyrax/dashboard/collections/_show_actions.html.erb_spec.rb
Labels: in progress

#2875 Fix for #2873 - CSRF Exception after adding to Collections/Sharing
  app/assets/javascripts/hyrax.js
  app/assets/javascripts/hyrax/turbolinks_events.js
  app/views/hyrax/my/_collection_action_menu.html.erb
  spec/features/dashboard/collection_spec.rb
  spec/support/selectors.rb
Labels: in progress

#2856 Add manage proxies to left menu
  app/assets/javascripts/hyrax/proxy_rights.js
  app/controllers/hyrax/depositors_controller.rb
  app/presenters/hyrax/menu_presenter.rb
  app/views/hyrax/dashboard/_index_partials/_proxy_rights.html.erb
  app/views/hyrax/dashboard/profiles/_edit_primary.html.erb
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
  app/views/hyrax/depositors/index.html.erb
  config/locales/hyrax.en.yml
  config/routes.rb
  spec/controllers/hyrax/depositors_controller_spec.rb
  spec/features/proxy_spec.rb
  spec/presenters/hyrax/menu_presenter_spec.rb
  spec/views/hyrax/dashboard/_sidebar.html.erb_spec.rb
  spec/views/hyrax/dashboard/profiles/edit.html.erb_spec.rb
  spec/views/hyrax/depositors/index.html.erb_spec.rb
Labels: in progress

#2845 Remove Your pronoun from breadcrumbs
  app/views/hyrax/my/collections/_tabs.html.erb
  app/views/hyrax/my/works/_tabs.html.erb
  config/locales/hyrax.en.yml
  spec/controllers/hyrax/collections_controller_spec.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/controllers/hyrax/file_sets_controller_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/features/collection_multi_membership_spec.rb
  spec/features/dashboard/collection_spec.rb
Labels: in progress

#2878 GenericWorksController: don't show 'Your Works' when logged out
  app/controllers/concerns/hyrax/breadcrumbs.rb
  spec/controllers/hyrax/collections_controller_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
Labels: in progress

#2886 Fix batch create as proxy
  app/controllers/hyrax/batch_uploads_controller.rb
  spec/controllers/hyrax/batch_uploads_controller_spec.rb
  spec/features/batch_create_spec.rb
Labels: in progress

#2891 update GenericWorksController spec for GH-2874
  spec/controllers/hyrax/generic_works_controller_spec.rb
Labels: in progress

#2896 improving on German locale
  config/locales/hyrax.de.yml
Labels: in progress

#2899 Fix link to duraspace wiki page that was never updated after name change
  .github/CONTRIBUTING.md
Labels: in progress

#2784 Refactor Relationships and Descriptions in Work Show. #1272
  app/assets/stylesheets/hyrax/_work-show.scss
  app/presenters/hyrax/presents_attributes.rb
  app/renderers/hyrax/renderers/attribute_renderer.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  app/views/hyrax/base/_metadata.html.erb
  app/views/hyrax/base/_relationships.html.erb
  app/views/hyrax/base/_relationships_parent_row.html.erb
  app/views/hyrax/base/_relationships_parent_rows.html.erb
  spec/features/work_show_spec.rb
  spec/renderers/hyrax/renderers/attribute_renderer_spec.rb
  spec/views/hyrax/base/_relationships.html.erb_spec.rb
Labels: in progress

#2128 Extends `ImportUrlJob` and `CreateWithRemoteFilesActor` to handle auth headers for cloud storage providers
  app/actors/hyrax/actors/create_with_remote_files_actor.rb
  app/jobs/import_url_job.rb
  spec/actors/hyrax/actors/create_with_remote_files_actor_spec.rb
Labels: in progress

#2893 Replace save with reindex on child collection
  app/models/concerns/hyrax/collection_nesting.rb
  app/services/hyrax/collections/nested_collection_persistence_service.rb
  spec/models/concerns/hyrax/collection_nesting_spec.rb
  spec/services/hyrax/collections/nested_collection_persistence_service_spec.rb
Labels: in progress

#2887 Only show files that users have permission to see.
  .rubocop.yml
  app/presenters/hyrax/work_show_presenter.rb
  app/views/hyrax/base/_items.html.erb
  config/features.rb
  spec/models/flipflop_spec.rb
  spec/views/hyrax/base/_items.html.erb_spec.rb
Labels: in progress

#2914 Fix long collection and admin set titles in facet label dropdowns to …
  app/assets/stylesheets/hyrax/dashboard.scss
Labels: in progress

#2908 Force loading of UV
  app/assets/javascripts/hyrax/turbolinks_events.js
Labels: in progress

#2911 Use :test `QueueAdapter` in specs
  spec/actors/hyrax/actors/file_set_actor_spec.rb
  spec/actors/hyrax/actors/generic_work_actor_spec.rb
  spec/controllers/hyrax/file_sets_controller_spec.rb
  spec/controllers/hyrax/transfers_controller_spec.rb
  spec/features/batch_create_spec.rb
  spec/features/create_work_admin_spec.rb
  spec/features/create_work_spec.rb
  spec/jobs/attach_files_to_work_job_spec.rb
  spec/jobs/batch_create_job_spec.rb
  spec/jobs/create_work_job_spec.rb
  spec/services/hyrax/workflow/grant_edit_to_depositor_spec.rb
  spec/services/hyrax/workflow/grant_read_to_depositor_spec.rb
  spec/services/hyrax/workflow/revoke_edit_from_depositor_spec.rb
  spec/spec_helper.rb
Labels: in progress

#2870 Shows modal when user cannot delete collection
  app/assets/javascripts/hyrax/collections.js
  app/views/hyrax/dashboard/collections/_list_collections.html.erb
  app/views/hyrax/my/collections/_modal_delete_collections_deny.html.erb
  app/views/hyrax/my/collections/index.html.erb
  config/locales/hyrax.en.yml
  spec/features/dashboard/collection_spec.rb
Labels: in progress

#2929 Update Travis badge on README.md to represent branch
  README.md
Labels: in progress

#2926 Pin simple-form to fix build
  hyrax.gemspec
Labels: in progress

#2916 Update links to samvera wiki from hydra wiki.
  .github/CODE_OF_CONDUCT.md
Labels: in progress

#2928 Update Travis badge on README.md to represent branch
  README.md
Labels: in progress

#2923 Note that template creates default collection types
  README.md
Labels: ready

#2934 Handle empty string in `member_of_collection_ids`
  app/actors/hyrax/actors/collections_membership_actor.rb
  spec/actors/hyrax/actors/collections_membership_actor_spec.rb
Labels: in progress

#2932 Convert ES6 syntax to ES5 syntax so Uglifier can deal with it.
  app/assets/javascripts/hyrax/collections.js
Labels: in progress

#2922 in relationship tab a work can't be put in two single work collection…
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/views/hyrax/base/_form_visibility_error.html.erb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/features/collection_multi_membership_spec.rb
  spec/support/selectors.rb
Labels: in progress

#2641 Improved /downloads request for status 401 with no permissions.
  app/controllers/hyrax/downloads_controller.rb
  lib/generators/hyrax/assets_generator.rb
  lib/generators/hyrax/templates/app/assets/images/unauthorized.png
  spec/controllers/hyrax/downloads_controller_spec.rb
Labels: in progress

#2924 limit the exposure of the permissions_attributes deprecation warning for collections
  app/controllers/hyrax/dashboard/collections_controller.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
Labels: ready

#2942 Update to Collections Edit sharing tab add participants button dynami…
  app/assets/javascripts/hyrax/collections.js
  app/views/hyrax/dashboard/collections/_form_share.html.erb
Labels: in progress

#2941 remove "my shares" <li> from search dropdown
  app/views/catalog/_search_form.html.erb
Labels: in progress

#2945 Collection Types > Participants tab UI updates
  app/assets/stylesheets/hyrax/_collection_types.scss
  app/views/hyrax/admin/collection_types/_form.html.erb
  app/views/hyrax/admin/collection_types/_form_participant_table.html.erb
  app/views/hyrax/admin/collection_types/_form_participants.html.erb
  config/locales/hyrax.en.yml
Labels: in progress

#2905 Disable discard_flash_if_xhr behavior
  lib/generators/hyrax/install_generator.rb
  spec/features/collection_type_spec.rb
Labels: in progress

#2950 Collection Types Edit Add Participants fix Add group and user via AJA…
  app/assets/javascripts/hyrax/collection_types.es6
  app/assets/stylesheets/hyrax/_collection_types.scss
  app/views/hyrax/admin/collection_types/_form_participant_table.html.erb
  app/views/hyrax/admin/collection_types/edit.html.erb
  spec/views/hyrax/admin/collection_types/_form_participants.html.erb_spec.rb
Labels: in progress

#2935 do not require admin_set_id attribute for work update
  app/actors/hyrax/actors/default_admin_set_actor.rb
  app/services/hyrax/default_middleware_stack.rb
  spec/actors/hyrax/actors/default_admin_set_actor_spec.rb
  spec/actors/hyrax/actors/generic_work_actor_spec.rb
  spec/controllers/hyrax/generic_works_controller_json_spec.rb
  spec/features/embargo_spec.rb
  spec/services/hyrax/default_middleware_stack_spec.rb
Labels: ready

#2879 set read_access on admin sets excluding registered and public groups
  app/controllers/hyrax/admin/admin_sets_controller.rb
  app/models/admin_set.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/models/hyrax/permission_template_access.rb
  app/services/hyrax/admin_set_create_service.rb
  app/services/hyrax/collections/migration_service.rb
  app/views/hyrax/admin/admin_sets/_show_actions.html.erb
  app/views/hyrax/admin/admin_sets/show.html.erb
  config/locales/hyrax.en.yml
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/factories/admin_sets_lw.rb
  spec/factories/collections.rb
  spec/factory_tests/adminsets_factory_spec.rb
  spec/factory_tests/collections_factory_spec.rb
  spec/models/admin_set_spec.rb
  spec/services/hyrax/collections/migration_service_spec.rb
  spec/services/hyrax/collections/permissions_create_service_spec.rb
  spec/services/hyrax/collections/permissions_service_spec.rb
  spec/views/hyrax/admin/admin_sets/_show_actions.html.erb_spec.rb
  spec/views/hyrax/admin/admin_sets/show.html.erb_spec.rb
Labels: in progress

#2948 Fix batch editing of permissions UI and functionality
  .rubocop_fixme.yml
  app/assets/javascripts/hyrax/batch_edit.js
  app/controllers/hyrax/batch_edits_controller.rb
  app/views/hyrax/batch_edits/edit.html.erb
  spec/controllers/hyrax/batch_edits_controller_spec.rb
  spec/features/batch_edit_spec.rb
  spec/support/features/batch_edit_actions.rb
Labels: in progress

#2952 Create a Collections JavaScript Utilities Class
  app/assets/javascripts/hyrax.js
  app/assets/javascripts/hyrax/app.js.erb
  app/assets/javascripts/hyrax/collection_types.es6
  app/assets/javascripts/hyrax/collections.js
  app/assets/javascripts/hyrax/collections_utils.es6
  app/assets/javascripts/hyrax/collections_v2.es6
  app/views/hyrax/admin/collection_types/_form_participants.html.erb
  app/views/hyrax/admin/collection_types/index.html.erb
  config/locales/hyrax.en.yml
Labels: in progress

#2951 Add managed access to list of collections under Managed Collections tab
  app/presenters/hyrax/admin_set_presenter.rb
  app/presenters/hyrax/collection_presenter.rb
  app/views/hyrax/dashboard/collections/_default_group.html.erb
  app/views/hyrax/dashboard/collections/_list_collections.html.erb
  app/views/hyrax/my/collections/_list_collections.html.erb
  config/locales/hyrax.en.yml
  spec/features/dashboard/collection_spec.rb
  spec/presenters/hyrax/admin_set_presenter_spec.rb
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/views/hyrax/dashboard/collections/_default_group.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_list_collections.html.erb_spec.rb
  spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb
Labels: in progress

#2953 Refactor tab change modal and add to collection type form
  app/assets/javascripts/hyrax.js
  app/assets/javascripts/hyrax/content_blocks.js
  app/assets/javascripts/hyrax/nav_safety.js
  app/views/hyrax/admin/collection_types/_form.html.erb
  app/views/hyrax/content_blocks/_form.html.erb
  app/views/hyrax/content_blocks/_modal_content_block.html.erb
  app/views/shared/_nav_safety_modal.html.erb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  lib/generators/hyrax/templates/config/tinymce.yml
  spec/features/edit_content_block_admin_spec.rb
Labels: in progress

#2936 make badge color configurable for collection types
  app/controllers/hyrax/admin/collection_types_controller.rb
  app/forms/hyrax/forms/admin/collection_type_form.rb
  app/presenters/hyrax/collection_presenter.rb
  app/services/hyrax/collection_types/create_service.rb
  app/views/catalog/_index_header_list_collection.html.erb
  app/views/hyrax/admin/collection_types/_form.html.erb
  app/views/hyrax/admin/collection_types/_form_appearance.html.erb
  app/views/hyrax/collections/_list_collections.html.erb
  app/views/hyrax/collections/show.html.erb
  app/views/hyrax/dashboard/collections/_collection_title.html.erb
  app/views/hyrax/dashboard/collections/_list_collections.html.erb
  app/views/hyrax/my/collections/_list_collections.html.erb
  config/locales/hyrax.en.yml
  lib/generators/hyrax/templates/db/migrate/20180406202557_add_badge_color_to_collection_types.rb.erb
  spec/forms/hyrax/forms/admin/collection_type_form_spec.rb
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/services/hyrax/collection_types/create_service_spec.rb
  spec/views/hyrax/admin/collection_types/_form.html.erb_spec.rb
  spec/views/hyrax/admin/collection_types/_form_appearance.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/show.html.erb_spec.rb
Labels: in progress

#2958 Update broken GitHub documentation link
  .github/CONTRIBUTING.md
Labels: in progress

#2961 Update translations for 2.1.0
  Gemfile
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/locales/simple_form.en.yml
  lib/generators/hyrax/templates/config/locales/hyrax.en.yml
  spec/controllers/hyrax/admin/strategies_controller_spec.rb
Labels: in progress

#2968 Fix the Admin::StrategiesController spec
  spec/controllers/hyrax/admin/strategies_controller_spec.rb
Labels: backport needed

#2971 Hide UniversalViewer when representative isn't an image
  app/presenters/hyrax/work_show_presenter.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
Labels: in progress

#2970 Improve on German language (native Speaker)
  config/locales/hyrax.de.yml
Labels: in progress

#2972 Hide UniversalViewer when representative isn't an image
  app/presenters/hyrax/work_show_presenter.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
Labels: in progress
