Repository samvera/hyrax, pull requests merged in 2018-02, with the labels that each got.

#2633 temporarily pin jasmine to < 2.99 until tests can be updated to work with jasmine 3.0
  hyrax.gemspec
Labels: in progress

#2635 Subcollection pagination
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/services/hyrax/collections/collection_member_service.rb
  app/views/hyrax/collections/_paginate.html.erb
  app/views/hyrax/collections/_subcollection_list.html.erb
  app/views/hyrax/dashboard/collections/_subcollection_list.html.erb
  lib/generators/hyrax/templates/db/seeds.rb
  spec/features/collection_spec.rb
  spec/features/dashboard/collection_spec.rb
  spec/views/hyrax/collections/_subcollection_list.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_subcollection_list.html.erb_spec.rb
Labels: collections/admin sets, in progress

#2639 Make default admin set the first item in relationship tab
  app/views/hyrax/base/_form_relationships.html.erb
  spec/features/create_work_admin_spec.rb
Labels: in progress

#2643 temporary pin of capybara to < 2.18.0 to avoid test failures with the latest version
  hyrax.gemspec
Labels: in progress

#2636 Reindex everything
  app/indexers/hyrax/repository_reindexer.rb
  app/models/concerns/hyrax/collection_nesting.rb
  app/services/hyrax/adapters/nesting_index_adapter.rb
  app/services/hyrax/collections/nested_collection_query_service.rb
  config/initializers/samvera-nesting_indexer_initializer.rb
  spec/indexers/hyrax/repository_reindexer_spec.rb
  spec/models/concerns/hyrax/collection_nesting_spec.rb
  spec/services/hyrax/adapters/nesting_index_adapter_spec.rb
Labels: collections/admin sets, in progress

#2640 Pass an array of collection type gid strings to where query
  app/services/hyrax/multiple_membership_checker.rb
  spec/services/hyrax/multiple_membership_checker_spec.rb
Labels: collections/admin sets, in progress

#2658 Use analytics fixture in analytics spec tests
  spec/fixtures/config/analytics.yml
  spec/lib/hyrax/analytics_spec.rb
  spec/test_app_templates/lib/generators/test_app_generator.rb
Labels: in progress

#2661 Initial spec coverage for Analytics::Base
  app/services/hyrax/analytics/base.rb
  app/services/hyrax/analytics/google_analytics.rb
  app/services/hyrax/analytics/matomo.rb
  hyrax.gemspec
  spec/services/hyrax/analytics/base_spec.rb
  spec/services/hyrax/analytics/google_analytics_spec.rb
  spec/services/hyrax/analytics/matomo_spec.rb
Labels: in progress

#2663 Pins parser and simple_form to fix travis builds
  hyrax.gemspec
Labels: in progress

#2653 Add specific validation for modal select element values by disabling submit button
  app/assets/javascripts/hyrax/collections.js
  app/assets/javascripts/hyrax/collections_forms.js
  app/views/hyrax/my/collections/_modal_add_subcollection.html.erb
  app/views/hyrax/my/collections/_modal_add_to_collection.html.erb
Labels: collections/admin sets, in progress

#2632 add FlipFlop for redesigned analytics
  app/controllers/hyrax/stats_controller.rb
  config/features.rb
Labels: Analytics, in progress

#2656 fixed typo in banner page.
  config/locales/hyrax.en.yml
Labels: in progress

#2662 Parent collection pagination
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/presenters/hyrax/collection_presenter.rb
  app/search_builders/hyrax/nested_collections_parent_search_builder.rb
  app/services/hyrax/collections/nested_collection_query_service.rb
  app/views/hyrax/collections/_show_parent_collections.html.erb
  app/views/hyrax/collections/show.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
  app/views/hyrax/dashboard/collections/show.html.erb
  lib/generators/hyrax/templates/db/seeds.rb
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/views/hyrax/collections/_show_parent_collections.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_parent_collections.html.erb_spec.rb
Labels: in progress

#2674 Fix broken piwik include in gemspec
  hyrax.gemspec
Labels: in progress

#2667 refactor collection factory to avoid fedora save unless specifically requested
  spec/authorities/qa/authorities/collections_spec.rb
  spec/factories/collections.rb
  spec/factories/collections_factory.rb
  spec/factories/object_id.rb
  spec/factory_tests/collections_factory_spec.rb
  spec/services/hyrax/collections/permissions_service_spec.rb
  spec/services/hyrax/collections_service_spec.rb
  spec/services/hyrax/multiple_membership_checker_spec.rb
Labels: collections/admin sets, in progress

#2659 Display collection type as badge
  app/views/hyrax/collections/_list_collections.html.erb
  app/views/hyrax/dashboard/collections/_list_collections.html.erb
  app/views/hyrax/my/collections/_list_collections.html.erb
  spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb
Labels: in progress

#2682 switch for new vs old analytics
  app/models/hyrax/statistic.rb
Labels: in progress

#2683 Initial documentation for Analytics::Base
  app/services/hyrax/analytics/base.rb
  app/services/hyrax/analytics/google_analytics.rb
  app/services/hyrax/analytics/matomo.rb
  spec/services/hyrax/analytics/base_spec.rb
  spec/services/hyrax/analytics/google_analytics_spec.rb
  spec/services/hyrax/analytics/matomo_spec.rb
Labels: in progress

#2684 Addressing temporal spec failure
  spec/models/file_set_spec.rb
Labels: in progress

#2652 Add title to admin set edit form
  app/views/hyrax/admin/admin_sets/edit.html.erb
  config/locales/hyrax.en.yml
  spec/features/dashboard/collection_spec.rb
Labels: collections/admin sets, in progress

#2695 Analytics initializer with Matomo
  app/services/hyrax/analytics/matomo.rb
  app/views/_analytics.html.erb
  app/views/_ga.html.erb
  app/views/_matomo.html.erb
  app/views/layouts/_head_tag_content.html.erb
  config/initializers/analytics.rb
  hyrax.gemspec
  lib/generators/hyrax/templates/config/analytics.yml
Labels: Analytics, in progress

#2687 fix single membership and add single/multi-membership spec tests
  app/controllers/hyrax/dashboard/collection_members_controller.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/services/hyrax/multiple_membership_checker.rb
  app/views/hyrax/my/works/_batch_actions.html.erb
  spec/features/collection_multi_membership_spec.rb
Labels: collections/admin sets, in progress

#2688 adjust presenter to manage value for subcollection_counts and collect…
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/presenters/hyrax/collection_presenter.rb
  app/views/hyrax/collections/show.html.erb
  app/views/hyrax/dashboard/collections/show.html.erb
  spec/features/collection_spec.rb
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/views/hyrax/dashboard/collections/show.html.erb_spec.rb
Labels: in progress

#2699 Use gender-neutral pronouns in favor of gender binary-based ones
  app/jobs/user_edit_profile_event_job.rb
  spec/jobs/user_edit_profile_event_job_spec.rb
Labels: in progress

#2692 Wire up nesting relationship delete buttons
  app/assets/javascripts/hyrax/collections_forms.js
  app/controllers/hyrax/dashboard/nest_collections_controller.rb
  app/forms/hyrax/forms/dashboard/nest_collection_form.rb
  app/services/hyrax/collections/nested_collection_persistence_service.rb
  app/views/hyrax/dashboard/collections/_form.html.erb
  app/views/hyrax/dashboard/collections/_form_relationships.html.erb
  app/views/hyrax/dashboard/collections/_modal_remove_from_collection.html.erb
  app/views/hyrax/dashboard/collections/_modal_remove_sub_collection.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
  app/views/hyrax/dashboard/collections/_subcollection_list.html.erb
  app/views/hyrax/dashboard/collections/show.html.erb
  config/locales/hyrax.en.yml
  config/routes.rb
  spec/controllers/hyrax/dashboard/nest_collections_controller_spec.rb
  spec/forms/hyrax/forms/dashboard/nest_collection_form_spec.rb
  spec/routing/dashboard_routes_spec.rb
  spec/services/hyrax/collections/nested_collection_persistence_service_spec.rb
  spec/views/hyrax/dashboard/collections/_form_relationships.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_parent_collections.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_subcollection_list.html.erb_spec.rb
Labels: collections/admin sets, in progress

#2693 Depositor should always be able to see their own work.
  app/search_builders/hyrax/filter_suppressed_with_roles.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/search_builders/hyrax/work_search_builder_spec.rb
Labels: in progress

#2671 Add embargo and lease links to admin dashboard in tasks section
  app/views/hyrax/dashboard/sidebar/_tasks.html.erb
  spec/views/hyrax/dashboard/_sidebar.html.erb_spec.rb
Labels: in progress

#2706 Add repository activity link to dashboard page
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
  config/locales/hyrax.en.yml
  spec/views/hyrax/dashboard/_sidebar.html.erb_spec.rb
Labels: in progress

#2721 Hyrax 2.1.0.beta1 release
  README.md
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  lib/hyrax/version.rb
  template.rb
Labels: in progress

#2655 Update RuboCop support; use Bixby style guide
  .rubocop.yml
  Gemfile
  app/actors/hyrax/actors/file_set_actor.rb
  app/actors/hyrax/actors/interpret_visibility_actor.rb
  app/actors/hyrax/actors/model_actor.rb
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/controllers/hyrax/api/items_controller.rb
  app/controllers/hyrax/transfers_controller.rb
  app/controllers/hyrax/users_controller.rb
  app/forms/hyrax/forms/permission_template_form.rb
  app/forms/hyrax/forms/work_form.rb
  app/helpers/hyrax/citations_behaviors/common_behavior.rb
  app/helpers/hyrax/citations_behaviors/formatters/chicago_formatter.rb
  app/helpers/hyrax/file_set_helper.rb
  app/helpers/hyrax/hyrax_helper_behavior.rb
  app/helpers/hyrax/trophy_helper.rb
  app/inputs/multi_value_select_input.rb
  app/models/admin_set.rb
  app/models/concerns/hyrax/ability.rb
  app/models/concerns/hyrax/suppressible.rb
  app/models/featured_work_list.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/services/hyrax/admin_set_create_service.rb
  app/services/hyrax/analytics.rb
  app/services/hyrax/collection_types/create_service.rb
  app/services/hyrax/collections/permissions_create_service.rb
  hyrax.gemspec
  lib/generators/hyrax/models_generator.rb
  lib/hyrax/configuration.rb
  spec/factories/file_sets.rb
  spec/helpers/hyrax/ability_helper_spec.rb
  spec/services/hyrax/qa_select_service_spec.rb
  tasks/hyrax_dev.rake
Labels: in progress

#2731 Strip query params from manifest url to avoid bad url for IIIF icon in UV share panel
  app/views/hyrax/base/_representative_media.html.erb
  spec/views/hyrax/base/show.html.erb_spec.rb
Labels: in progress

#2729 Turn off turbolinks for Edit Collection from dashboard action menu
  app/views/hyrax/my/_collection_action_menu.html.erb
Labels: in progress

#2725 Depend on factory_bot rather than factory_bot_rails
  hyrax.gemspec
Labels: in progress
