Repository samvera/hyrax, pull requests merged in 2018-10, with the labels that each got.

#3316 Allow use of 0.5 version of iiif_manifest
  hyrax.gemspec
Labels: in progress

#3318 Prepare release 2.3.3
  README.md
  lib/hyrax/version.rb
  template.rb
Labels: in progress

#3282 Mark tests that were optional in Travis as optional in CircleCI
  spec/features/collection_multi_membership_spec.rb
  spec/features/work_show_spec.rb
  spec/spec_helper.rb
Labels: in progress

#3320 Remove duplicate thumbnail on featured works
  app/views/hyrax/homepage/_featured.html.erb
Labels: in progress

#3317 Remove datatables class from All Works display table, which was causi…
  app/views/hyrax/dashboard/works/_default_group.html.erb
Labels: In Discussion, in progress

#3239 Setup initial work creation transaction
  hyrax.gemspec
  lib/hyrax/transactions.rb
  lib/hyrax/transactions/container.rb
  lib/hyrax/transactions/create_work.rb
  lib/hyrax/transactions/steps/ensure_admin_set.rb
  lib/hyrax/transactions/steps/ensure_permission_template.rb
  lib/hyrax/transactions/steps/save_work.rb
  lib/hyrax/transactions/steps/set_default_admin_set.rb
  lib/hyrax/transactions/steps/set_modified_date.rb
  lib/hyrax/transactions/steps/set_uploaded_date.rb
  spec/factories/generic_works.rb
  spec/hyrax/transactions/create_work_spec.rb
  spec/hyrax/transactions/steps/ensure_admin_set_spec.rb
  spec/hyrax/transactions/steps/ensure_permission_template_spec.rb
  spec/hyrax/transactions/steps/save_work_spec.rb
  spec/hyrax/transactions/steps/set_default_admin_set_spec.rb
  spec/hyrax/transactions/steps/set_modified_date_spec.rb
  spec/hyrax/transactions/steps/set_uploaded_date_spec.rb
Labels: in progress

#2859 Don't hit external services for view tests
  app/views/hyrax/my/_collection_action_menu.html.erb
  spec/presenters/hyrax/presenter_renderer_spec.rb
  spec/spec_helper.rb
  spec/views/catalog/index.html.erb_spec.rb
  spec/views/hyrax/admin/admin_sets/_show_actions.html.erb_spec.rb
  spec/views/hyrax/admin/admin_sets/_show_document_list_row.html.erb_spec.rb
  spec/views/hyrax/admin/admin_sets/index.html.erb_spec.rb
  spec/views/hyrax/admin/admin_sets/index.json.erb_spec.rb
  spec/views/hyrax/admin/collection_types/_form_metadata_admin_set.html.erb_spec.rb
  spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb
  spec/views/hyrax/admin/collection_types/index.html.erb_spec.rb
  spec/views/hyrax/admin/stats/show.html.erb_spec.rb
  spec/views/hyrax/base/_attribute_rows.html.erb_spec.rb
  spec/views/hyrax/base/_attributes.html.erb_spec.rb
  spec/views/hyrax/base/_form_rendering.html.erb_spec.rb
  spec/views/hyrax/base/_items.html.erb_spec.rb
  spec/views/hyrax/base/_relationships.html.erb_spec.rb
  spec/views/hyrax/base/file_manager.html.erb_spec.rb
  spec/views/hyrax/base/show.json.jbuilder_spec.rb
  spec/views/hyrax/collections/_show_document_list_row.html.erb_spec.rb
  spec/views/hyrax/collections/_show_parent_collections.html.erb_spec.rb
  spec/views/hyrax/collections/_subcollection_list.html.erb_spec.rb
  spec/views/hyrax/collections/show.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_form_share.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_form_share_table.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_document_list_row.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_subcollection_list.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/edit.html.erb_spec.rb
  spec/views/hyrax/dashboard/profiles/show.html.erb_spec.rb
  spec/views/hyrax/file_sets/_show_characterization_details.html.erb_spec.rb
  spec/views/hyrax/file_sets/_single_use_links.html.erb_spec.rb
  spec/views/hyrax/homepage/_sortable_featured.html.erb_spec.rb
  spec/views/hyrax/my/_collection_action_menu.html.erb_spec.rb
  spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb
  spec/views/hyrax/users/index.html.erb_spec.rb
  spec/views/hyrax/users/show.html.erb_spec.rb
Labels: in progress

#3332 Wrap long file names in fileset and work show page
  app/assets/stylesheets/hyrax/_work-show.scss
  app/views/hyrax/base/_member.html.erb
  app/views/hyrax/file_sets/_file_set_title.erb
  app/views/hyrax/users/_activity_log.html.erb
Labels: in progress

#3345 Avoid deprecated static Factory attributes
  spec/factories/generic_works.rb
Labels: in progress

#3313 Adds Select All to Collections Dashboard (new: fixed earlier alignment issues)
  app/assets/stylesheets/hyrax/_file-listing.scss
  app/helpers/hyrax/batch_edits_helper.rb
  app/views/hyrax/my/collections/_default_group.html.erb
  spec/helpers/hyrax/batch_edits_helper_spec.rb
Labels: priority

#3079 Ordered_members actor to add file_sets to work in one action
  app/actors/hyrax/actors/create_with_files_ordered_members_actor.rb
  app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb
  app/actors/hyrax/actors/file_set_ordered_members_actor.rb
  app/actors/hyrax/actors/ordered_members_actor.rb
  app/jobs/attach_files_to_work_with_ordered_members_job.rb
  spec/actors/hyrax/actors/create_with_files_ordered_members_actor_spec.rb
  spec/actors/hyrax/actors/create_with_remote_files_ordered_members_actor_spec.rb
  spec/actors/hyrax/actors/file_set_ordered_members_actor_spec.rb
  spec/actors/hyrax/actors/ordered_members_actor_spec.rb
  spec/jobs/attach_files_to_work_with_ordered_members_job_spec.rb
Labels: in progress

#3338 Allow readonly works to be added to collections
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/views/hyrax/base/_show_actions.html.erb
  spec/features/work_show_spec.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
  spec/views/hyrax/base/_show_actions.html.erb_spec.rb
Labels: in progress

#3343 Add documentation about the purpose of the source parameter
  app/assets/javascripts/hyrax/collections.js
Labels: in progress

#3357 Update copyright year in blacklight locales
  lib/generators/hyrax/templates/config/locales/hyrax.de.yml
  lib/generators/hyrax/templates/config/locales/hyrax.en.yml
  lib/generators/hyrax/templates/config/locales/hyrax.es.yml
  lib/generators/hyrax/templates/config/locales/hyrax.fr.yml
  lib/generators/hyrax/templates/config/locales/hyrax.it.yml
  lib/generators/hyrax/templates/config/locales/hyrax.zh.yml
Labels: in progress

#2853 Remove unused partial
  app/views/hyrax/dashboard/collections/_form_default_group_delt.html.erb
Labels: in progress

#3342 Remove unnecessary case clause from NestCollectionsController#redirec…
  app/controllers/hyrax/dashboard/nest_collections_controller.rb
Labels: in progress

#3344 Update documentation about html attributes
  app/views/hyrax/my/collections/_list_collections.html.erb
Labels: in progress

#3334 [Request review] Fixes #3245 - Add flash notice for Batch Deactivation of Expired Emba…
  app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  spec/controllers/hyrax/embargoes_controller_spec.rb
Labels: in progress

#3359 Add form group wrappers to fieldsets on Edit work page
  app/views/hyrax/base/_form_rendering.html.erb
  app/views/hyrax/base/_form_representative.html.erb
  app/views/hyrax/base/_form_thumbnail.html.erb
Labels: in progress
