Repository samvera/hyrax, pull requests merged in 2018-03, with the labels that each got.

#2722 Hide the search option when "All" is the only option in the search box dropdown.
  app/views/catalog/_search_form.html.erb
  spec/features/search_spec.rb
Labels: in progress

#2709 Make work head tag title SEO friendly.
  app/presenters/hyrax/work_show_presenter.rb
  spec/features/work_show_spec.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
  spec/views/hyrax/base/show.html.erb_spec.rb
Labels: in progress

#2710 connect to GA using Google's API gem
  app/models/analytics/statistic.rb
  app/models/hyrax/statistic.rb
  app/services/hyrax/analytics/google_analytics.rb
  config/initializers/analytics.rb
  spec/services/hyrax/analytics/google_analytics_spec.rb
Labels: in progress

#2734 Analytics collections
  app/assets/javascripts/hyrax/dashboard_actions.js
  app/assets/stylesheets/hyrax/dashboard.scss
  app/controllers/hyrax/dashboard_controller.rb
  app/search_builders/hyrax/admin_set_search_builder.rb
  app/services/hyrax/admin_set_service.rb
  app/services/hyrax/collections_count_service.rb
  app/services/hyrax/count_service.rb
  app/views/hyrax/dashboard/_analytics_collections.html.erb
  app/views/hyrax/dashboard/_analytics_collections_ajax.html.erb
  app/views/hyrax/dashboard/show_admin.html.erb
  config/locales/hyrax.en.yml
  config/routes.rb
  spec/controllers/hyrax/dashboard_controller_spec.rb
  spec/routing/route_spec.rb
  spec/services/hyrax/collections_count_service_spec.rb
Labels: in progress

#2727 Clean up from wiring up remove collection relationships
  app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
  app/views/hyrax/dashboard/collections/_subcollection_list.html.erb
  spec/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb_spec.rb
Labels: collections/admin sets, in progress

#2739 Restores button for add child work.
  app/views/hyrax/base/_show_actions.html.erb
  spec/views/hyrax/base/_show_actions.html.erb_spec.rb
Labels: in progress

#2742 Revert to searching "member_of_collection_ids"
  app/search_builders/hyrax/collection_member_search_builder.rb
  spec/controllers/hyrax/collections_controller_spec.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/features/collection_multi_membership_spec.rb
  spec/features/collection_spec.rb
  spec/features/dashboard/collection_spec.rb
  spec/forms/hyrax/forms/collection_form_spec.rb
  spec/services/hyrax/collections/collection_member_service_spec.rb
Labels: in progress

#2646 Don't try to clean up temp directories and files that may still be in use
  app/jobs/import_url_job.rb
  spec/jobs/import_url_job_spec.rb
Labels: in progress

#2741 Add `data-sort` attributes to dataTables rows to support date sort
  app/views/hyrax/notifications/_notifications.html.erb
  app/views/hyrax/transfers/_received.html.erb
  app/views/hyrax/transfers/_sent.html.erb
  app/views/hyrax/users/_activity_log.html.erb
Labels: in progress

#2748 Select admin set already assigned when editing and default when new
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/views/hyrax/base/_form_relationships.html.erb
  spec/features/create_work_admin_spec.rb
  spec/features/edit_work_spec.rb
Labels: in progress

#2752 Fix the IIIF share icon link and accurately test it
  app/views/hyrax/base/_representative_media.html.erb
  spec/features/work_show_spec.rb
  spec/views/hyrax/base/show.html.erb_spec.rb
Labels: in progress

#2751 Use DataTables plugin to display tables
  app/assets/javascripts/hyrax/dashboard_actions.js
  app/controllers/hyrax/dashboard_controller.rb
  app/views/hyrax/dashboard/_analytics_collections.html.erb
  app/views/hyrax/dashboard/_analytics_collections_ajax.html.erb
  config/routes.rb
  spec/controllers/hyrax/dashboard_controller_spec.rb
  spec/routing/route_spec.rb
Labels: in progress

#2750 Initial implementation of ResourceStat model
  app/models/resource_stat.rb
  lib/generators/hyrax/templates/db/migrate/20180301101033_create_resource_stats.rb.erb
  spec/models/resource_stat_spec.rb
Labels: in progress

#2758 Lock `simple_form` less strictly
  hyrax.gemspec
Labels: in progress

#2740 Fixing locale de v2.1.0.beta1
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
Labels: in progress

#2768 fixes situation in which embargo update receives file_set ids in its …
  app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
  spec/controllers/hyrax/embargoes_controller_spec.rb
Labels: in progress

#2771 Add initial finders for ResourceStat
  app/models/resource_stat.rb
  spec/models/resource_stat_spec.rb
Labels: in progress

#2765 Dependency backports
  .travis.yml
  app/search_builders/hyrax/catalog_search_builder.rb
  hyrax.gemspec
  spec/features/batch_edit_spec.rb
  spec/features/browse_dashboard_works_spec.rb
  spec/features/ownership_transfer_spec.rb
Labels: in progress

#2772 Charts updated
  app/assets/javascripts/hyrax/dashboard_actions.js
  app/assets/stylesheets/hyrax/dashboard.scss
  app/controllers/hyrax/dashboard_controller.rb
  app/presenters/hyrax/admin/repository_growth_presenter.rb
  app/presenters/hyrax/admin/repository_object_presenter.rb
  app/presenters/hyrax/admin/user_activity_presenter.rb
  app/views/hyrax/dashboard/_analytics_collections.html.erb
  app/views/hyrax/dashboard/_analytics_growth.html.erb
  app/views/hyrax/dashboard/_analytics_object_counts.html.erb
  app/views/hyrax/dashboard/show_admin.html.erb
  config/initializers/chartkick.rb
  config/locales/hyrax.en.yml
  config/routes.rb
  lib/generators/hyrax/chartkick_generator.rb
  lib/generators/hyrax/install_generator.rb
  spec/presenters/hyrax/admin/repository_growth_presenter_spec.rb
  spec/presenters/hyrax/admin/user_activity_presenter_spec.rb
  spec/routing/route_spec.rb
Labels: in progress

#2754 Add `data-sort` attributes to dataTables rows to support date sort
  app/views/hyrax/notifications/_notifications.html.erb
  app/views/hyrax/transfers/_received.html.erb
  app/views/hyrax/transfers/_sent.html.erb
  app/views/hyrax/users/_activity_log.html.erb
Labels: in progress

#2745 GA download event from Work Items drop-down
  app/views/hyrax/file_sets/_actions.html.erb
  spec/views/hyrax/file_sets/_actions.html.erb_spec.rb
Labels: in progress

#2770 Update to search results layout
  app/assets/stylesheets/hyrax/_catalog.scss
  app/assets/stylesheets/hyrax/_settings.scss
  app/views/catalog/_index_header_list_collection.html.erb
  app/views/catalog/_index_header_list_default.html.erb
  app/views/catalog/_index_list_default.html.erb
  app/views/catalog/_thumbnail_list_collection.html.erb
  app/views/catalog/_thumbnail_list_default.html.erb
  config/locales/hyrax.en.yml
Labels: in progress

#2781 Bump version to 2.0.2
  README.md
  lib/hyrax/version.rb
  template.rb
Labels: in progress

#2775 Updates to dashboard collection show ui
  app/assets/stylesheets/hyrax/_collections.scss
  app/assets/stylesheets/hyrax/_modal.scss
  app/views/hyrax/dashboard/collections/_collection_title.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
  app/views/hyrax/dashboard/collections/_subcollection_list.html.erb
  app/views/hyrax/dashboard/collections/show.html.erb
Labels: in progress

#2790 Set video width to force it to stay inside column
  app/views/hyrax/file_sets/media_display/_audio.html.erb
  app/views/hyrax/file_sets/media_display/_video.html.erb
Labels: in progress

#2794 Create user link with user object instead of user_key
  app/models/proxy_deposit_request.rb
  spec/controllers/hyrax/transfers_controller_spec.rb
Labels: in progress

#2766 make branding a configurable setting.
  app/controllers/hyrax/admin/collection_types_controller.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/forms/hyrax/forms/admin/collection_type_form.rb
  app/models/hyrax/collection_type.rb
  app/services/hyrax/collection_types/create_service.rb
  app/views/hyrax/admin/collection_types/_form_settings.html.erb
  app/views/hyrax/dashboard/collections/_form.html.erb
  config/locales/hyrax.en.yml
  lib/generators/hyrax/templates/db/migrate/20180302200051_add_branding_to_collection_type.rb.erb
  spec/controllers/hyrax/admin/collection_types_controller_spec.rb
  spec/factories/collection_types.rb
  spec/factories/collections.rb
  spec/factory_tests/collections_factory_spec.rb
  spec/features/collection_type_spec.rb
  spec/features/dashboard/collection_spec.rb
  spec/forms/hyrax/forms/admin/collection_type_form_spec.rb
  spec/javascripts/settings_spec.js
  spec/models/collection_spec.rb
  spec/models/hyrax/collection_type_spec.rb
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/services/hyrax/collection_types/create_service_spec.rb
  spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb
Labels: in progress

#2787 Consolidate collections javascript files, and fix remove parent and s…
  app/assets/javascripts/hyrax.js
  app/assets/javascripts/hyrax/collections.js
  app/assets/javascripts/hyrax/collections_forms.js
  app/views/hyrax/dashboard/collections/_modal_remove_from_collection.html.erb
  app/views/hyrax/dashboard/collections/_modal_remove_sub_collection.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
  app/views/hyrax/dashboard/collections/_subcollection_list.html.erb
  app/views/hyrax/dashboard/collections/show.html.erb
  app/views/hyrax/my/collections/_modal_add_subcollection.html.erb
  app/views/hyrax/my/collections/_modal_add_to_collection.html.erb
  spec/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_parent_collections.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_subcollection_list.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/show.html.erb_spec.rb
Labels: in progress

#2782 Add unique and returning site-wide stats
  app/models/resource_stat.rb
  app/presenters/hyrax/admin/user_activity_presenter.rb
  app/services/hyrax/statistics/site/returning_visitors.rb
  app/services/hyrax/statistics/site/unique_visitors.rb
  spec/models/resource_stat_spec.rb
  spec/presenters/hyrax/admin/user_activity_presenter_spec.rb
  spec/services/hyrax/statistics/site/returning_visitors_spec.rb
  spec/services/hyrax/statistics/site/unique_visitors_spec.rb
Labels: in progress

#2789 Work show view modifications for collections
  app/helpers/hyrax/collections_helper.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/search_builders/hyrax/parent_collection_search_builder.rb
  app/services/hyrax/collection_member_service.rb
  app/views/hyrax/base/_relationships_parent_rows.html.erb
  spec/factories/collection_types.rb
  spec/factories/collections.rb
  spec/factories/collections_factory.rb
  spec/features/create_work_spec.rb
  spec/helpers/hyrax/collections_helper_spec.rb
  spec/search_builders/hyrax/parent_collection_search_builder_spec.rb
  spec/services/hyrax/collection_member_service_spec.rb
  spec/views/hyrax/admin/admin_sets/_show_document_list_row.html.erb_spec.rb
  spec/views/hyrax/base/_attributes.html.erb_spec.rb
  spec/views/hyrax/base/_relationships.html.erb_spec.rb
Labels: in progress

#2805 display error message when collection type title already exists.
  app/controllers/hyrax/admin/collection_types_controller.rb
  spec/features/collection_type_spec.rb
Labels: in progress

#2808 Document enabling and configuring ffmpeg
  README.md
Labels: in progress

#2807 Remove more/less from parent list pagination
  app/presenters/hyrax/collection_presenter.rb
  app/views/hyrax/collections/_show_parent_collections.html.erb
  app/views/hyrax/dashboard/collections/_show_parent_collections.html.erb
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/views/hyrax/collections/_show_parent_collections.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_parent_collections.html.erb_spec.rb
Labels: in progress

#2806 Add commas to collection link list
  app/helpers/hyrax/collections_helper.rb
Labels: in progress

#2732 Don't show 'Remove Highlight Designation' in edit user profile without highlighted works.
  app/views/hyrax/dashboard/profiles/_trophy_edit.html.erb
  spec/views/hyrax/dashboard/profiles/_trophy_edit.html.erb_spec.rb
  spec/views/hyrax/dashboard/profiles/edit.html.erb_spec.rb
Labels: in progress

#2783 Update test to use new column name
  lib/generators/hyrax/work/templates/feature_spec.rb.erb
Labels: in progress

#2803 Reindex work after visibility change
  app/actors/hyrax/actors/interpret_visibility_actor.rb
  spec/features/edit_work_spec.rb
Labels: in progress

#2799 Adds confirmation alert before leaving unsaved content blocks
  app/assets/javascripts/hyrax/content_blocks.js
  app/views/hyrax/content_blocks/_form.html.erb
  app/views/hyrax/content_blocks/_modal_content_block.html.erb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  spec/features/edit_content_block_admin_spec.rb
Labels: in progress

#2814 adding selector in app.js that CollectionControls requires for Partic…
  app/assets/javascripts/hyrax/app.js.erb
  spec/features/dashboard/collection_spec.rb
Labels: in progress

#2826 Remove parser restriction
  hyrax.gemspec
Labels: in progress

#2823 [WIP] Update user and admin dash titles
  app/views/hyrax/dashboard/show_admin.html.erb
  config/locales/hyrax.en.yml
  spec/controllers/hyrax/citations_controller_spec.rb
  spec/controllers/hyrax/collections_controller_spec.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/controllers/hyrax/file_sets_controller_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/features/dashboard/display_admin_dashboard_spec.rb
  spec/features/dashboard/display_dashboard_spec.rb
Labels: in progress

#2831 Provide more leniency for a missing database connection during initialization
  lib/hyrax/engine.rb
Labels: in progress

#2835 Change 'Admininstration' to 'Dashboard' in breadcrumbs
  config/locales/hyrax.en.yml
  spec/controllers/hyrax/admin/appearances_controller_spec.rb
  spec/controllers/hyrax/admin/features_controller_spec.rb
  spec/controllers/hyrax/admin/workflow_roles_controller_spec.rb
  spec/controllers/hyrax/admin/workflows_controller_spec.rb
  spec/controllers/hyrax/content_blocks_controller_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/controllers/hyrax/my/collections_controller_spec.rb
  spec/controllers/hyrax/my/works_controller_spec.rb
  spec/controllers/hyrax/pages_controller_spec.rb
Labels: in progress

#2828 add facet for collections to dashboard -> works index
  app/controllers/hyrax/my/works_controller.rb
  app/controllers/hyrax/my_controller.rb
  app/views/hyrax/my/_facet_pivot.html.erb
  config/locales/hyrax.en.yml
  spec/features/dashboard/all_works.rb
Labels: in progress

#2832 Change nested forms in collections > edit > sharing tab to ajax to fix broken submission
  app/assets/javascripts/hyrax/collections.js
  app/assets/stylesheets/hyrax/_collections.scss
  app/views/hyrax/dashboard/collections/_form_share.html.erb
  app/views/hyrax/dashboard/collections/_form_share_table.html.erb
  spec/views/hyrax/dashboard/collections/_form_share.erb_spec.rb
Labels: in progress

#2830 Solve errors with visibility & reindexing
  app/actors/hyrax/actors/interpret_visibility_actor.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/models/concerns/hyrax/collection_nesting.rb
  app/views/hyrax/batch_select/_add_button.html.erb
  config/locales/hyrax.en.yml
  spec/actors/hyrax/actors/lease_actor_spec.rb
  spec/factories/generic_works.rb
  spec/models/concerns/hyrax/collection_nesting_spec.rb
Labels: in progress

#2833 Focusable Skip to Content Link
  app/assets/stylesheets/hyrax/_accessibility.scss
  app/assets/stylesheets/hyrax/dashboard.scss
  app/views/layouts/hyrax.html.erb
  app/views/layouts/hyrax/dashboard.html.erb
Labels: ready

#2809 Works table server
  app/assets/images/sm-loader.gif
  app/assets/javascripts/hyrax.js
  app/assets/javascripts/hyrax/admin/analytics_stats.es6
  app/assets/javascripts/hyrax/app.js.erb
  app/assets/javascripts/hyrax/dashboard_actions.js
  app/controllers/hyrax/analytics_controller.rb
  app/controllers/hyrax/dashboard_controller.rb
  app/search_builders/hyrax/admin_set_search_builder.rb
  app/search_builders/hyrax/analytics_works_search_builder.rb
  app/services/hyrax/collections_count_service.rb
  app/services/hyrax/count_service.rb
  app/services/hyrax/works_count_service.rb
  app/views/hyrax/dashboard/_analytics_growth.html.erb
  app/views/hyrax/dashboard/_analytics_object_counts.html.erb
  app/views/hyrax/dashboard/_analytics_works.html.erb
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
  config/routes.rb
  spec/controllers/hyrax/analytics_controller_spec.rb
  spec/controllers/hyrax/dashboard_controller_spec.rb
  spec/features/create_work_admin_spec.rb
  spec/routing/route_spec.rb
  spec/search_builders/hyrax/analytics_works_search_builder_spec.rb
  spec/services/hyrax/works_count_service_spec.rb
Labels: in progress

#2851 Add backend updates per dev comments
  app/presenters/hyrax/menu_presenter.rb
  app/views/_analytics.html.erb
  app/views/hyrax/admin/reports/works/status.html.erb
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
Labels: in progress

#2857 fixes scenario when application has no models
  app/search_builders/hyrax/abstract_type_relation.rb
  spec/search_builders/hyrax/abstract_type_relation_spec.rb
Labels: in progress

#2855 Fail eagerly when adding invalid participants to collection types
  app/services/hyrax/collection_types/create_service.rb
  spec/services/hyrax/collection_types/create_service_spec.rb
Labels: in progress

#2849 2837 add sidebar to management pages
  app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
  app/controllers/concerns/hyrax/leases_controller_behavior.rb
  app/controllers/hyrax/batch_edits_controller.rb
  app/controllers/hyrax/embargoes_controller.rb
  app/controllers/hyrax/file_sets_controller.rb
  app/controllers/hyrax/leases_controller.rb
  app/views/hyrax/batch_edits/edit.html.erb
  app/views/hyrax/embargoes/edit.html.erb
  app/views/hyrax/embargoes/index.html.erb
  app/views/hyrax/file_sets/edit.html.erb
  app/views/hyrax/leases/edit.html.erb
  app/views/hyrax/leases/index.html.erb
  spec/controllers/hyrax/batch_edits_controller_spec.rb
  spec/controllers/hyrax/embargoes_controller_spec.rb
  spec/controllers/hyrax/file_sets_controller_spec.rb
  spec/controllers/hyrax/leases_controller_spec.rb
Labels: in progress

#2816 Handle byte range requests for local files
  .rubocop_fixme.yml
  app/controllers/concerns/hyrax/local_file_downloads_controller_behavior.rb
  app/controllers/hyrax/downloads_controller.rb
  spec/controllers/hyrax/downloads_controller_spec.rb
Labels: in progress

#2862 Revert "fixes scenario when application has no models"
  app/search_builders/hyrax/abstract_type_relation.rb
  spec/search_builders/hyrax/abstract_type_relation_spec.rb
Labels: in progress

#2866 propagate batch permissions changes to file sets
  app/controllers/hyrax/batch_edits_controller.rb
  spec/controllers/hyrax/batch_edits_controller_spec.rb
Labels: in progress

#2867 maintains I18n selections on works and files stats links
  app/presenters/hyrax/file_set_presenter.rb
  app/presenters/hyrax/work_show_presenter.rb
  spec/presenters/hyrax/file_set_presenter_spec.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
Labels: in progress

#2869 Use same thumbnail service for admin sets and collections.
  app/indexers/hyrax/admin_set_indexer.rb
  spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb
Labels: in progress

#2871 sets proper depositor when attaching files in background job
  app/jobs/attach_files_to_work_job.rb
  spec/jobs/attach_files_to_work_job_spec.rb
Labels: in progress

#2861 ensures only one set of controls when a work has multiple titles
  app/views/hyrax/base/_work_title.erb
  spec/features/work_show_spec.rb
Labels: in progress
