Repository samvera/hyrax, pull requests merged in 2019-10, with the labels that each got.

#4059 [wings] Implement `#name` for classes generated by `OrmConverter`
  lib/wings/orm_converter.rb
  spec/wings/orm_converter_spec.rb
Labels: wings

#4053 Introduce a `SimpleWork` for testing, and a factory for it
  spec/factories/hyrax_resource.rb
  spec/factories/hyrax_work.rb
  spec/spec_helper.rb
  spec/support/book_resource.rb
  spec/support/simple_work.rb
  spec/wings/active_fedora_converter_spec.rb
Labels: wings

#4072 Upgrade Capybara
  hyrax.gemspec
  spec/features/collection_type_spec.rb
  spec/features/dashboard/collection_spec.rb
  spec/features/edit_content_block_admin_spec.rb
  spec/features/edit_pages_admin.spec.rb
  spec/features/notifications_spec.rb
  spec/features/proxy_spec.rb
  spec/views/hyrax/admin/collection_types/index.html.erb_spec.rb
  spec/views/hyrax/base/_form_files.html.erb_spec.rb
  spec/views/hyrax/base/unauthorized.html.erb_spec.rb
Labels: dependency

#4084 add base FileSet resource; add find_files custom query
  app/models/hyrax/file_set.rb
  app/services/hyrax/custom_queries/find_file_metadata.rb
  app/services/hyrax/custom_queries/navigators/find_files.rb
  lib/hyrax/specs/shared_specs/hydra_works.rb
  lib/wings.rb
  lib/wings/services/custom_queries/find_file_metadata.rb
  spec/factories/hyrax_file_metadata.rb
  spec/factories/hyrax_file_set.rb
  spec/factories/strategies/valkyrie_resource.rb
  spec/models/hyrax/file_set_spec.rb
  spec/services/hyrax/custom_queries/find_file_metadata_spec.rb
  spec/services/hyrax/custom_queries/navigators/find_files_spec.rb
  spec/spec_helper.rb
  spec/support/simple_work.rb
  spec/wings/services/custom_queries/find_file_metadata_spec.rb
Labels: wings

#4077 Don't filter `member_of_collection_ids` by PCDM type
  app/services/hyrax/custom_queries/navigators/child_collections_navigator.rb
Labels: wings

#4078 Test the custom `find_access_control_for(resource:)` valkyrie query
  app/services/hyrax/custom_queries/find_access_control.rb
  spec/services/hyrax/custom_queries/find_access_control_spec.rb
Labels: wings

#4079 Remove unneeded TODO in `child_works_navigator`
  app/services/hyrax/custom_queries/navigators/child_filesets_navigator.rb
  app/services/hyrax/custom_queries/navigators/child_works_navigator.rb
Labels: wings

#4088 Support `i18n` for Valkyrie `#human_readable_type`
  app/models/hyrax/resource.rb
  config/locales/hyrax.en.yml
  spec/models/hyrax/file_set_spec.rb
  spec/models/hyrax/pcdm_collection_spec.rb
  spec/models/hyrax/work_spec.rb
Labels: wings

#4044 Remove unauthorized.png from generator
  lib/generators/hyrax/assets_generator.rb
Labels: backport needed

#4134 [wings] Reinstate quoting of `::Collection` and `FileSet`
  lib/wings.rb
Labels: wings
