Repository samvera/hyrax, pull requests merged in 2019-04, with the labels that each got.

#3695 Add wings query for find_inverse_references_by
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress

#3697 Orders members when converting to AF objects.
  lib/wings/active_fedora_converter.rb
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/hydra/works/models/concerns/work_valkyrie_behavior.rb
  lib/wings/model_transformer.rb
  lib/wings/valkyrie/query_service.rb
  spec/wings/active_fedora_converter_spec.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/file_set_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3714 add navigator services to find child members for various model parts
  lib/wings/navigators/child_collections_navigator.rb
  lib/wings/navigators/child_filesets_navigator.rb
  lib/wings/navigators/child_works_navigator.rb
  lib/wings/valkyrie/query_service.rb
  spec/wings/navigators/child_collections_navigator_spec.rb
  spec/wings/navigators/child_filesets_navigator_spec.rb
  spec/wings/navigators/child_works_navigator_spec.rb
Labels: wings

#3746 valkyrize file_actor adding file_node to hold metadata_node values from active fedora
  app/actors/hyrax/actors/file_actor.rb
  app/models/job_io_wrapper.rb
  app/services/hyrax/versioning_service.rb
  lib/wings.rb
  lib/wings/models/file_node.rb
  lib/wings/models/multi_checksum.rb
  lib/wings/services/file_node_builder.rb
  lib/wings/valkyrie/persister.rb
  spec/actors/hyrax/actors/file_actor_spec.rb
  spec/models/job_io_wrapper_spec.rb
  spec/wings/models/file_node_spec.rb
Labels: wings

#3703 Revert "Move instance variable out of actor and into environment"
  app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb
  app/actors/hyrax/actors/environment.rb
  spec/actors/hyrax/actors/create_with_remote_files_ordered_members_actor_spec.rb
Labels: in progress

#3696 Replace pul_uv_rails
  app/assets/stylesheets/hyrax/_viewer.scss
  app/helpers/hyrax/iiif_helper.rb
  app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
  hyrax.gemspec
  lib/generators/hyrax/install_generator.rb
  lib/generators/hyrax/templates/package.json
  lib/generators/hyrax/templates/uv.html
  lib/generators/hyrax/templates/uv_config.json
  lib/hyrax/engine.rb
  spec/features/work_show_spec.rb
  spec/helpers/hyrax/iiif_helper_spec.rb
  spec/test_app_templates/lib/generators/test_app_generator.rb
  spec/views/hyrax/base/show.html.erb_spec.rb
Labels: in progress

#3755 Fix template url and update rails version
  README.md
Labels: in progress

#3758 make sure when depositing by proxy that user gets rights over files.
  app/jobs/attach_files_to_work_job.rb
  spec/features/create_work_spec.rb
Labels: in progress

#3709 when tabbing in relationship tab, allow user to reach "Add" buttons.
  app/views/hyrax/base/_form_child_work_relationships.html.erb
  app/views/hyrax/base/_form_member_of_collections.html.erb
Labels: in progress

#3554 input form has title as single entry, but the title def stays multiple
  app/forms/hyrax/forms/admin_set_form.rb
  app/forms/hyrax/forms/collection_form.rb
  app/forms/hyrax/forms/work_form.rb
  app/indexers/hyrax/basic_metadata_indexer.rb
  app/models/admin_set.rb
  app/models/concerns/hyrax/basic_metadata.rb
  app/models/concerns/hyrax/solr_document/metadata.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/views/hyrax/dashboard/collections/edit.html.erb
  app/views/records/edit_fields/_alt_title.html.erb
  app/views/records/edit_fields/_title.html.erb
  spec/features/dashboard/collection_spec.rb
  spec/forms/hyrax/forms/batch_upload_form_spec.rb
  spec/forms/hyrax/forms/collection_form_spec.rb
  spec/forms/hyrax/forms/work_form_spec.rb
  spec/forms/hyrax/generic_work_form_spec.rb
  spec/views/records/edit_fields/_alt_title.html.erb_spec.rb
  spec/views/records/edit_fields/_title.html.erb_spec.rb
Labels: in progress

#3759 center headings in work listed in dashboard.
  app/views/hyrax/dashboard/works/_default_group.html.erb
  app/views/hyrax/dashboard/works/_list_works.html.erb
  app/views/hyrax/my/works/_default_group.html.erb
  app/views/hyrax/my/works/_list_works.html.erb
Labels: in progress

#3761 Improve the universal viewer deployment
  app/helpers/hyrax/iiif_helper.rb
  lib/generators/hyrax/install_generator.rb
  lib/generators/hyrax/templates/package.json
  lib/generators/hyrax/templates/uv-config.json
  lib/generators/hyrax/templates/uv.html
  spec/features/work_show_spec.rb
  spec/helpers/hyrax/iiif_helper_spec.rb
  spec/test_app_templates/lib/generators/test_app_generator.rb
Labels: in progress

#3767 fix guillemets in German locale
  config/locales/hyrax.de.yml
Labels: in progress
