Repository samvera/hyrax, pull requests merged in 2019-06, with the labels that each got.

#3772 Use the original file's width and height instead of assuming 640x480
  app/presenters/hyrax/displays_image.rb
Labels: in progress

#3776 fix current logic error in displaying/hiding feature/unfeature buttons
  app/views/hyrax/base/_show_actions.html.erb
Labels: Check CLA

#3814 use active_fedora storage adapter to save file and connect it to the file_set
  app/actors/hyrax/actors/file_actor.rb
  app/models/job_io_wrapper.rb
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
  lib/hyrax/configuration.rb
  lib/wings.rb
  lib/wings/hydra/works/services/add_file_node_to_file_set.rb
  lib/wings/models/file_node.rb
  lib/wings/services/file_node_builder.rb
  lib/wings/valkyrie/persister.rb
  lib/wings/valkyrie/storage/active_fedora.rb
  spec/models/job_io_wrapper_spec.rb
  spec/wings/models/file_node_spec.rb
Labels: wings

#3827 fix failing file_actor tests
  app/presenters/hyrax/member_presenter_factory.rb
  app/services/hyrax/versioning_service.rb
  spec/actors/hyrax/actors/file_actor_spec.rb
Labels: wings

#3828 Replace ActiveFedora::Base.find
  app/actors/hyrax/actors/add_to_work_actor.rb
  app/actors/hyrax/actors/apply_order_actor.rb
  app/actors/hyrax/actors/attach_members_actor.rb
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
  app/controllers/hyrax/batch_edits_controller.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/controllers/hyrax/permissions_controller.rb
  app/controllers/hyrax/single_use_links_viewer_controller.rb
  app/controllers/hyrax/workflow_actions_controller.rb
  app/forms/hyrax/forms/batch_edit_form.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/services/hyrax/persist_directly_contained_output_file_service.rb
  app/services/hyrax/thumbnail_path_service.rb
  app/services/hyrax/workflow/deposited_notification.rb
  lib/wings/valkyrie/query_service.rb
  spec/actors/hyrax/actors/file_set_actor_spec.rb
  spec/actors/hyrax/actors/ordered_members_actor_spec.rb
  spec/controllers/hyrax/single_use_links_viewer_controller_spec.rb
  spec/features/create_work_spec.rb
  spec/features/static_pages_spec.rb
  spec/features/work_show_spec.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: wings

#3842 create association in fileset to the file
  app/actors/hyrax/actors/file_actor.rb
  lib/wings/hydra/works/services/add_file_node_to_file_set.rb
  lib/wings/services/file_node_builder.rb
Labels: wings

#3845 Short-circuit the actor stack when the user can't edit works
  app/actors/hyrax/actors/add_to_work_actor.rb
  spec/features/actor_stack_spec.rb
Labels: backport needed

#3844 Normalize Valkyrie configuration
  app/actors/hyrax/actors/add_to_work_actor.rb
  app/actors/hyrax/actors/apply_order_actor.rb
  app/actors/hyrax/actors/attach_members_actor.rb
  app/actors/hyrax/actors/base_actor.rb
  app/actors/hyrax/actors/file_actor.rb
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
  app/controllers/hyrax/batch_edits_controller.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/controllers/hyrax/permissions_controller.rb
  app/controllers/hyrax/single_use_links_viewer_controller.rb
  app/controllers/hyrax/workflow_actions_controller.rb
  app/forms/hyrax/forms/batch_edit_form.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/models/job_io_wrapper.rb
  app/services/hyrax/persist_directly_contained_output_file_service.rb
  app/services/hyrax/thumbnail_path_service.rb
  app/services/hyrax/workflow/deposited_notification.rb
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
  lib/hyrax.rb
  lib/hyrax/configuration.rb
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/models/file_node.rb
  lib/wings/services/id_converter_service.rb
  lib/wings/valkyrie/storage/active_fedora.rb
  spec/actors/hyrax/actors/file_actor_spec.rb
  spec/actors/hyrax/actors/file_set_actor_spec.rb
  spec/actors/hyrax/actors/ordered_members_actor_spec.rb
  spec/controllers/hyrax/single_use_links_viewer_controller_spec.rb
  spec/lib/hyrax/configuration_spec.rb
Labels: wings

#3852 Move Navigators under CustomQueries
  app/services/hyrax/custom_queries/navigators/child_collections_navigator.rb
  app/services/hyrax/custom_queries/navigators/child_filesets_navigator.rb
  app/services/hyrax/custom_queries/navigators/child_works_navigator.rb
  lib/wings.rb
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/navigators/child_collections_navigator.rb
  lib/wings/navigators/child_filesets_navigator.rb
  lib/wings/navigators/child_works_navigator.rb
  spec/services/hyrax/custom_queries/navigators/child_collections_navigator_spec.rb
  spec/services/hyrax/custom_queries/navigators/child_filesets_navigator_spec.rb
  spec/services/hyrax/custom_queries/navigators/child_works_navigator_spec.rb
  spec/support/matchers/match_valkyrie_ids_with_af_ids.rb
Labels: wings

#3849 Refactor `AttachMembersActor` for Valkyrie membership adding
  app/actors/hyrax/actors/attach_members_actor.rb
  app/actors/hyrax/actors/collections_membership_actor.rb
  spec/actors/hyrax/actors/attach_members_actor_spec.rb
Labels: wings

#3851 [wings] Use Valkyrie for `DepositedNotification`
  app/services/hyrax/workflow/deposited_notification.rb
Labels: wings

#3858 Replace calls to `solr_name`
  app/controllers/hyrax/homepage_controller.rb
  app/controllers/hyrax/my/works_controller.rb
  app/controllers/hyrax/my_controller.rb
  app/helpers/hyrax/hyrax_helper_behavior.rb
  app/indexers/hyrax/indexes_workflow.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/models/concerns/hyrax/file_set/querying.rb
  app/models/concerns/hyrax/human_readable_type.rb
  app/models/concerns/hyrax/solr_document/characterization.rb
  app/models/concerns/hyrax/solr_document/metadata.rb
  app/models/concerns/hyrax/solr_document_behavior.rb
  app/renderers/hyrax/renderers/faceted_attribute_renderer.rb
  app/search_builders/hyrax/collection_search_builder.rb
  app/search_builders/hyrax/deposit_search_builder.rb
  app/services/hyrax/statistics/file_sets/by_format.rb
  app/services/hyrax/statistics/works/by_resource_type.rb
  app/views/records/show_fields/_based_near.html.erb
  app/views/records/show_fields/_creator.html.erb
  app/views/records/show_fields/_keyword.html.erb
  app/views/records/show_fields/_language.html.erb
  app/views/records/show_fields/_publisher.html.erb
  app/views/records/show_fields/_resource_type.html.erb
  app/views/records/show_fields/_subject.html.erb
  config/initializers/samvera-nesting_indexer_initializer.rb
  lib/generators/hyrax/templates/catalog_controller.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/controllers/hyrax/homepage_controller_spec.rb
  spec/helpers/hyrax/dashboard_helper_behavior_spec.rb
  spec/helpers/hyrax_helper_spec.rb
  spec/models/file_set_spec.rb
  spec/views/hyrax/base/_attributes.html.erb_spec.rb
Labels: wings

#3867 [wings] Implement visibility mapping for Valkyrie resources
  app/models/hyrax/resource.rb
  app/services/hyrax/resource_visibility_propagator.rb
  app/services/hyrax/visibility_map.rb
  app/services/hyrax/visibility_propagator.rb
  app/services/hyrax/visibility_reader.rb
  app/services/hyrax/visibility_writer.rb
  spec/models/hyrax/resource_spec.rb
  spec/services/hyrax/resource_visibility_propagator_spec.rb
  spec/services/hyrax/visibility_reader_spec.rb
  spec/services/hyrax/visibility_writer_spec.rb
Labels: wings

#3876 mark test as pending
  spec/wings/models/file_node_spec.rb
Labels: wings

#3874 Add tests for file_set and to_file_node methods in JobIoWrapper
  app/models/job_io_wrapper.rb
  spec/models/job_io_wrapper_spec.rb
Labels: wings
