Repository samvera/hyrax, pull requests merged in 2019-03, with the labels that each got.

#3559 Use [* TO *] to work with old and new versions of AF and Solr
  app/search_builders/hyrax/embargo_search_builder.rb
  app/search_builders/hyrax/lease_search_builder.rb
Labels: in progress

#3544 Backport current CircleCI config to 2.x-stable
  .circleci/config.yml
  spec/spec_helper.rb
Labels: in progress

#3562 [wings] Setup Valkyrie adapters when Wings is required
  lib/hyrax/configuration.rb
  lib/wings.rb
Labels: in progress, wings

#3561 Resolves RSpec issues for CircleCI tests against 2.x releases
  hyrax.gemspec
Labels: in progress

#3565 Add Ruby 2.6 to the build matrix
  .circleci/config.yml
Labels: in progress

#3550 add rights notes metadata to work.
  app/forms/hyrax/forms/work_form.rb
  app/indexers/hyrax/basic_metadata_indexer.rb
  app/models/concerns/hyrax/basic_metadata.rb
  app/models/concerns/hyrax/solr_document/metadata.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  config/locales/hyrax.en.yml
  spec/forms/hyrax/forms/batch_upload_form_spec.rb
  spec/forms/hyrax/forms/work_form_spec.rb
  spec/presenters/hyrax/work_show_presenter_spec.rb
  spec/views/hyrax/base/show.html.erb_spec.rb
Labels: in progress

#3564 Allow i18n via data properties like on all the other fields
  app/assets/javascripts/hyrax/editor/controlled_vocabulary.es6
Labels: in progress

#3566 Add support for Ruby 2.6; drop 2.3
  README.md
Labels: in progress

#3563 [wings] Make Valkyrie a production dependency
  hyrax.gemspec
Labels: in progress, wings

#3567 Bump version to 3.0.0-beta2
  README.md
  lib/hyrax/version.rb
  template.rb
Labels: in progress

#3582 Run i18n normalization & automatic translations for 3.0.0-beta2
  Gemfile
  config/locales/hyrax.de.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
Labels: in progress

#3586 Implement "find_all" for Wings::Valkyrie::QueryService
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress, wings

#3603 Small i18n de update
  config/locales/hyrax.de.yml
Labels: in progress

#3545 Backport current CircleCI config to 2.0-stable
  .circleci/config.yml
  hyrax.gemspec
  spec/lib/hyrax/resource_sync/change_list_writer_spec.rb
  spec/services/hyrax/statistics/works/by_resource_type_spec.rb
  spec/spec_helper.rb
Labels: in progress

#3616 Implement "find_all_of_model" query
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress, wings

#3623 mints an id for newly created works using wings
  lib/wings/model_transformer.rb
  spec/wings/model_transformer_spec.rb
Labels: in progress, wings

#3624 implement #objects from pcdm_behavior
  lib/wings/active_fedora_converter.rb
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/model_transformer.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/model_transformer_spec.rb
  spec/wings/support/matchers/match_valkyrie_ids_with_af_ids.rb
  spec/wings_helper.rb
Labels: in progress, wings

#3621 Add find_by_alternate_identifier to wings query service
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress

#3631 Remove Wings::ResourceFactory
  lib/wings.rb
  lib/wings/resource_factory.rb
Labels: in progress

#3630 implement #object_ids from pcdm_behavior
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3635 setup infrastructure for including pcdm/works methods
  lib/wings/hydra/pcdm/models/concerns/collection_valkyrie_behavior.rb
  lib/wings/hydra/pcdm/models/concerns/object_valkyrie_behavior.rb
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/hydra/works/models/concerns/collection_valkyrie_behavior.rb
  lib/wings/hydra/works/models/concerns/file_set_valkyrie_behavior.rb
  lib/wings/hydra/works/models/concerns/work_valkyrie_behavior.rb
  lib/wings/model_transformer.rb
  spec/wings/hydra/pcdm/models/concerns/collection_valkyrie_behavior_spec.rb
  spec/wings/hydra/pcdm/models/concerns/object_valkyrie_behavior_spec.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/collection_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/file_set_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: wings

#3637 Remove Travis CI
  .travis.yml
  README.md
Labels: in progress

#3617 Add find_many_by_ids to wings query_service
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress, wings

#3632 [wings] Fix bug in YARD example for ModelTransformer
  lib/wings/model_transformer.rb
Labels: in progress, wings

#3636 define member_ids as ordered
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/model_transformer.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/model_transformer_spec.rb
Labels: in progress, wings

#3641 Rework class docs, reorganize ModelTransformer
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
Labels: in progress

#3640 returns valkryie adapter from hyrax configuration
  lib/hyrax.rb
  lib/hyrax/configuration.rb
  spec/lib/hyrax/configuration_spec.rb
Labels: in progress

#3646 Persister stores created & updated dates
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
  spec/wings/valkyrie/persister_spec.rb
Labels: in progress

#3634 Add new_record attribute to valkyrie resources in wings
  lib/wings/model_transformer.rb
  spec/wings/valkyrie/persister_spec.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress, wings

#3650 Update internal_resource to be a string instead of a constant
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
  lib/wings/valkyrie/query_service.rb
  spec/wings/model_transformer_spec.rb
Labels: in progress

#3651 define member_of_collection_ids for valkyrie resources
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/model_transformer.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
Labels: wings

#3648 Add remaining persister methods
  lib/wings/valkyrie/persister.rb
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/persister_spec.rb
Labels: in progress

#3653 move valkyrie replacements for hyrax/collection_behavior to file mirroring the hyrax directory structure
  app/models/concerns/hyrax/collection_behavior.rb
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/model_transformer.rb
  lib/wings/models/concerns/collection_behavior.rb
  lib/wings/services/id_converter_service.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/models/concerns/collection_behavior_spec.rb
  spec/wings/services/id_converter_service_spec.rb
Labels: wings

#3658 Backport of #3164 - Collection Thumbnails don't show in search results
  app/views/catalog/_thumbnail_list_collection.html.erb
  spec/features/search_spec.rb
  spec/views/catalog/_thumbnail_list_collection.html.erb_spec.rb
Labels: in progress

#3656 define member_object_ids for valkyrie resources
  README.md
  app/models/concerns/hyrax/collection_behavior.rb
  lib/wings/models/concerns/collection_behavior.rb
  spec/wings/models/concerns/collection_behavior_spec.rb
Labels: in progress, wings

#3667 Prep for a Hyrax 2.5.0 release
  README.md
  lib/hyrax/version.rb
  template.rb
Labels: in progress

#3660 Valkyrizes #works for Hydra::Works
  lib/wings/hydra/works/models/concerns/work_valkyrie_behavior.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3659 Wings persister saves a native valkyrie resource
  .rubocop_fixme.yml
  lib/hyrax.rb
  lib/hyrax/engine.rb
  lib/wings/active_fedora_converter.rb
  spec/wings/valkyrie/persister_spec.rb
Labels: in progress

#3642 Remove Travis CI
  .travis.yml
  README.md
Labels: in progress

#3546 Make Hyrax::Actors::TransactionRequest a no-op actor.
  app/actors/hyrax/actors/transactional_request.rb
  app/services/hyrax/default_middleware_stack.rb
  hyrax.gemspec
  spec/actors/hyrax/actors/transactional_request_spec.rb
Labels: in progress

#3678 [wings] Make Embargo, Lease, and Visibility work for `BaseActor#create`
  app/actors/hyrax/actors/base_actor.rb
  app/actors/hyrax/actors/environment.rb
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
  lib/wings/valkyrie/persister.rb
  spec/actors/hyrax/actors/generic_work_actor_spec.rb
  spec/actors/hyrax/actors/interpret_visibility_actor_spec.rb
  spec/wings/active_fedora_converter_spec.rb
  spec/wings/model_transformer_spec.rb
Labels: in progress

#3683 Run rspec at 4x parallelism in Circle CI
  .circleci/config.yml
Labels: in progress

#3677 add member_of, in_collections, and in_collection_ids methods for valkyrie resources
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3687 Adds a translated version of #child_work_ids
  lib/wings/hydra/works/models/concerns/work_valkyrie_behavior.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3681 convert valkyrie member_of_collection_ids to AF member_of_collections objects
  lib/wings/active_fedora_converter.rb
  spec/wings/active_fedora_converter_spec.rb
Labels: in progress, wings

#3684 Add method_missing to catch any unconverted methods
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/file_set_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3685 Implement `find_references_by` in wings query service
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress

#3689 Adds #child_file_sets for Hydra::Works::Works
  lib/wings/hydra/works/models/concerns/work_valkyrie_behavior.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3688 Run Circle at 10x concurrency
  .circleci/config.yml
Labels: in progress

#3682 Implement find_members in query_service
  lib/wings/valkyrie/query_service.rb
  spec/wings/valkyrie/query_service_spec.rb
Labels: in progress

#3686 Move internal dependencies into the main Engine body
  lib/hyrax/engine.rb
Labels: in progress

#3698 add clean_repo to model tests
  spec/wings/hydra/pcdm/models/concerns/collection_valkyrie_behavior_spec.rb
  spec/wings/hydra/pcdm/models/concerns/object_valkyrie_behavior_spec.rb
  spec/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/collection_valkyrie_behavior_spec.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3693 wings persister can save native valkyrie resource with a nested resource property
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
  lib/wings/transformer_value_mapper.rb
  spec/wings/transformer_value_mapper_spec.rb
  spec/wings/valkyrie/persister_spec.rb
Labels: in progress

#3691 allows for a native valkyrie resource to be deleted
  lib/wings/valkyrie/persister.rb
  spec/wings/valkyrie/persister_spec.rb
Labels: in progress

#3655 enforces only to use wings adapter for now
  .circleci/config.yml
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
  lib/hyrax/configuration.rb
  spec/lib/hyrax/configuration_spec.rb
Labels: in progress

#3701 generate test app or return true for job
  .circleci/config.yml
Labels: in progress

#3702 revert build job to always build
  .circleci/config.yml
Labels: in progress

#3708 Extract and translate strings.
  app/views/hyrax/collections/_sort_and_per_page.html.erb
  app/views/hyrax/dashboard/collections/_form_branding.html.erb
  app/views/hyrax/dashboard/collections/_form_share.html.erb
  app/views/hyrax/dashboard/collections/_sort_and_per_page.html.erb
  app/views/hyrax/file_sets/_show_actions.html.erb
  app/views/hyrax/file_sets/_show_details.html.erb
  app/views/hyrax/users/_vitals.html.erb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  spec/views/hyrax/collections/_sort_and_per_page.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_sort_and_per_page.html.erb_spec.rb
Labels: in progress

#3680 add abstract metadata to work
  app/forms/hyrax/forms/work_form.rb
  app/indexers/hyrax/basic_metadata_indexer.rb
  app/models/concerns/hyrax/basic_metadata.rb
  app/models/concerns/hyrax/solr_document/metadata.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  app/views/records/edit_fields/_abstract.html.erb
  config/locales/hyrax.en.yml
  spec/forms/hyrax/forms/batch_upload_form_spec.rb
  spec/forms/hyrax/forms/work_form_spec.rb
Labels: in progress

#3700 Adds #parent_works for Hydra::Works::Work behavior.
  lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb
  lib/wings/hydra/works/models/concerns/work_valkyrie_behavior.rb
  spec/wings/hydra/works/models/concerns/work_valkyrie_behavior_spec.rb
Labels: in progress, wings

#3699 maintains valkyrie id if it is specified
  lib/wings/active_fedora_converter.rb
  spec/wings/valkyrie/persister_spec.rb
Labels: in progress, wings
