Repository samvera/hyrax, pull requests merged in 2022-09, with the labels that each got.

#5831 Improving file handle life cycle
  app/services/hyrax/local_file_service.rb
Labels: notes-bugfix

#5748 remove deprecated method from CollectionsControllerBehavior
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
Labels: notes-deprecation

#5852 Index member_of_collection_ids for PcdmCollection
  app/indexers/hyrax/pcdm_collection_indexer.rb
  lib/hyrax/specs/shared_specs/indexers.rb
  spec/indexers/hyrax/pcdm_collection_indexer_spec.rb
Labels: backport needed

#5851 Don't default member_of_collection_ids in collection_params
  app/controllers/hyrax/dashboard/collections_controller.rb
  spec/controllers/hyrax/dashboard/collections_controller_with_resource_spec.rb
Labels: backport needed

#5874 Ensuring Hyrax::UserStatImporter returns false on exception
  app/services/hyrax/user_stat_importer.rb
Labels: backport needed, notes-bugfix

#5850 Use solr's graph query builder for nested collection queries
  app/actors/hyrax/actors/collections_membership_actor.rb
  app/controllers/hyrax/dashboard/collection_members_controller.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/forms/hyrax/forms/dashboard/nest_collection_form.rb
  app/indexers/hyrax/repository_reindexer.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/models/concerns/hyrax/collection_nesting.rb
  app/models/concerns/hyrax/work_behavior.rb
  app/search_builders/hyrax/dashboard/nested_collections_search_builder.rb
  app/services/hyrax/adapters/nesting_index_adapter.rb
  app/services/hyrax/collections/nested_collection_query_service.rb
  config/initializers/nesting_indexer_initializer.rb
  lib/hyrax/configuration.rb
  spec/actors/hyrax/actors/lease_actor_spec.rb
  spec/factories/collections.rb
  spec/factories/collections_factory.rb
  spec/factory_tests/collections_factory_spec.rb
  spec/features/edit_work_spec.rb
  spec/forms/hyrax/forms/dashboard/nest_collection_form_spec.rb
  spec/indexers/hyrax/repository_reindexer_spec.rb
  spec/lib/hyrax/configuration_spec.rb
  spec/models/collection_spec.rb
  spec/models/concerns/hyrax/collection_nesting_spec.rb
  spec/models/hyrax/work_behavior_spec.rb
  spec/search_builders/hyrax/dashboard/nested_collections_search_builder_spec.rb
  spec/services/hyrax/adapters/nesting_index_adapter_spec.rb
  spec/services/hyrax/collections/nested_collection_persistence_service_spec.rb
  spec/services/hyrax/collections/nested_collection_query_service_spec.rb
  spec/spec_helper.rb
Labels: valkyrization
