Repository samvera/hyrax, pull requests merged in 2022-06, with the labels that each got.

#5755 correctly derive paths for UploadedFileUploader
  app/uploaders/hyrax/uploaded_file_uploader.rb
Labels: backport needed

#5747 remove deprecated argument/attribute from GraphExporter
  app/services/hyrax/graph_exporter.rb
Labels: notes-deprecation

#5752 remove deprecated methods from NestCollectionsController
  app/controllers/hyrax/dashboard/nest_collections_controller.rb
Labels: notes-deprecation

#5694 always pull repo file if filepath param is missing
  app/jobs/characterize_job.rb
  app/jobs/create_derivatives_job.rb
  app/services/hyrax/working_directory.rb
  spec/jobs/characterize_job_spec.rb
  spec/jobs/create_derivatives_job_spec.rb
Labels: backport needed

#5757 add some basic documentation for CustomQueries
  app/services/hyrax/custom_queries.rb
Labels: notes-docs
