Repository samvera/hyrax, pull requests merged in 2023-03, with the labels that each got.

#5744 remove deprecated methods from CollectionBehavior
  spec/abilities/collection_ability_spec.rb
  spec/factories/collections.rb
  spec/factories/collections_factory.rb
  spec/features/dashboard/collection_spec.rb
  spec/models/collection_spec.rb
Labels: notes-deprecation

#5977 update the cc license config file for koppie
  .koppie/config/authorities/licenses.yml
Labels: notes-bugfix

#5746 remove deprecated #to_sipity_entity
  app/models/concerns/hyrax/suppressible.rb
  spec/features/workflow_state_changes_spec.rb
Labels: notes-deprecation

#5749 remove Blacklight 6 compatibility methods
  app/controllers/concerns/hyrax/controller.rb
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/controllers/hyrax/file_sets_controller.rb
  app/helpers/hyrax/hyrax_helper_behavior.rb
  app/services/hyrax/admin_set_service.rb
  app/services/hyrax/collections/nested_collection_query_service.rb
  app/services/hyrax/restriction_service.rb
  spec/controllers/hyrax/dashboard/nest_collections_controller_spec.rb
  spec/controllers/hyrax/dashboard/works_controller_spec.rb
  spec/controllers/hyrax/my/collections_controller_spec.rb
  spec/controllers/hyrax/my/works_controller_spec.rb
  spec/forms/hyrax/forms/admin_set_form_spec.rb
  spec/forms/hyrax/forms/collection_form_spec.rb
  spec/helpers/hyrax_helper_spec.rb
  spec/services/hyrax/admin_set_service_spec.rb
  spec/services/hyrax/collections_service_spec.rb
  spec/views/hyrax/base/_form.html.erb_spec.rb
  spec/views/hyrax/batch_uploads/_form.html.erb_spec.rb
Labels: notes-deprecation

#5996 chart: add extraDeploy template variable for extensibility
  chart/hyrax/Chart.yaml
  chart/hyrax/templates/extra-list.yaml
  chart/hyrax/values.yaml
Labels: notes-container
