Repository samvera/hyrax, pull requests merged in 2023-07, with the labels that each got.

#6106 Initialize query_service before tests
  spec/spec_helper.rb
Labels: notes-bugfix

#6104 4.x GA4 Reporting Support
  .dassie/config/analytics.yml
  app/assets/javascripts/hyrax/analytics_events.js
  app/controllers/hyrax/admin/analytics/collection_reports_controller.rb
  app/controllers/hyrax/admin/analytics/work_reports_controller.rb
  app/services/hyrax/analytics/ga4.rb
  app/views/hyrax/admin/analytics/collection_reports/index.html.erb
  app/views/hyrax/admin/analytics/work_reports/index.html.erb
  app/views/hyrax/base/_show_actions.html.erb
  app/views/hyrax/base/_work_button_row.html.erb
  app/views/hyrax/dashboard/_user_activity.html.erb
  app/views/hyrax/dashboard/show_admin.html.erb
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
  app/views/hyrax/file_sets/_show_actions.html.erb
  app/views/layouts/_head_tag_content.html.erb
  app/views/shared/_ga4.html.erb
  lib/generators/hyrax/templates/config/analytics.yml
Labels: notes-minor

#6098 5844 deactivated embargoes
  app/actors/hyrax/actors/embargo_actor.rb
  app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
  app/forms/hyrax/forms/work_embargo_form.rb
  app/indexers/hyrax/valkyrie_work_indexer.rb
  app/models/hyrax/resource.rb
  app/services/hyrax/embargo_manager.rb
  lib/hyrax/transactions/steps/save.rb
  spec/actors/hyrax/actors/embargo_actor_spec.rb
  spec/factories/hyrax_embargo.rb
  spec/factories/hyrax_resource.rb
  spec/models/hyrax/resource_spec.rb
  spec/services/hyrax/embargo_manager_spec.rb
Labels: notes-valkyrie, notes-bugfix

#6105 Stop testing middle ruby versions
  .circleci/config.yml
Labels: notes-minor

#6118 5844-save-embargoes-better
  app/models/hyrax/resource.rb
Labels: notes-valkyrie, notes-bugfix

#6108 add priv key from env for GA 4. Copies #6063 to the new GA4 code
  app/services/hyrax/analytics/ga4.rb
  app/services/hyrax/analytics/google.rb
Labels: notes-minor

#6123 Let Rails CLI that Hyrax is still an Engine
  bin/rails
  lib/hyrax/engine.rb
Labels: notes-bugfix

#6117 5844-set-embargo-date-as-datetime
  lib/hyrax/transactions/steps/save.rb
Labels: notes-valkyrie, notes-bugfix

#6107 add priv key from env for GA 4
  app/services/hyrax/analytics/ga4.rb
  app/services/hyrax/analytics/google.rb
  spec/lib/hyrax/analytics_spec.rb
Labels: notes-minor

#6112 5573-one-step-workflow
  lib/hyrax/active_fedora_dummy_model.rb
  spec/models/concerns/hyrax/solr_document_behavior_spec.rb
Labels: notes-valkyrie, notes-bugfix

#6088 5592 dashboard statistics page error
  .koppie/config/initializers/hyrax.rb
  app/models/hyrax/resource.rb
  app/search_builders/hyrax/valkyrie_abstract_type_relation.rb
  app/search_builders/hyrax/valkyrie_work_relation.rb
  app/services/hyrax/custom_queries/find_by_date_range.rb
  app/services/hyrax/custom_queries/find_count_by.rb
  app/services/hyrax/custom_queries/find_models_by_access.rb
  app/services/hyrax/statistics/depositors/summary.rb
  app/services/hyrax/statistics/over_time.rb
  app/services/hyrax/statistics/valkyrie_query_service.rb
  app/services/hyrax/statistics/works/count.rb
  lib/wings/active_fedora_converter.rb
  lib/wings/setup.rb
  spec/factories/generic_works.rb
  spec/services/hyrax/statistics/query_service_spec.rb
Labels: valk-rc
