Repository samvera/hyrax, pull requests merged in 2023-12, with the labels that each got.

#6484 Marks test suite as ActiveFedora-only, since presenter calls to multiple classes not Valkyrized.
  spec/presenters/hyrax/file_usage_spec.rb
Labels: valkyrization, notes-valkyrie

#6485 Adds active_fedora tag to AF-specific test in grant_read_job_spec.
  spec/jobs/hyrax/grant_read_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6487 Valkyrization: Fix failing tests in `spec/lib/hyrax/analytics_spec.rb`
  .koppie/config/analytics.yml
Labels: valkyrization, notes-valkyrie

#6488 Utilizes Valkyrie patterns for nested_collection_query_service_spec.
  spec/services/hyrax/collections/nested_collection_query_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6482 Utilizes Valkyrie patterns for catalog_controller_spec.
  config/metadata/basic_metadata.yaml
  spec/controllers/catalog_controller_spec.rb
  spec/spec_helper.rb
Labels: valkyrization, notes-valkyrie

#6489 Adds active_fedora tag to AF-specific tests in transfers_controller_spec.
  spec/controllers/hyrax/transfers_controller_spec.rb
Labels: valkyrization, notes-valkyrie

#6491 Valkyrization: Fix failing tests in `users_spec.rb`
  spec/features/users_spec.rb
Labels: valkyrization, notes-valkyrie

#6492 Valkyrization: Fix failing tests in `admin_set_member_service_spec.rb`
  spec/services/hyrax/admin_set_member_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6459 Makes spec/services/hyrax/file_set_fixity_check_service_spec.rb Dassie-only.
  spec/services/hyrax/file_set_fixity_check_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6490 Marks test suite as ActiveFedora-only, since controller calls to multiple classes not Valkyrized.
  spec/controllers/hyrax/stats_controller_spec.rb
Labels: valkyrization, notes-valkyrie

#6494 Marks test suite as ActiveFedora-only because the alternative Valkyrie form class has its own suite.
  spec/forms/hyrax/forms/admin_set_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6495 Move riiif dependent code to the generated riiif initializer
  .dassie/config/initializers/riiif.rb
  .koppie/config/initializers/riiif.rb
  app/models/concerns/hyrax/riiif_file.rb
  app/services/hyrax/riiif_file_resolver.rb
  lib/generators/hyrax/templates/config/initializers/riiif.rb
Labels: notes-bugfix

#6502 Add support for valkyrie resources to Ability
  app/models/concerns/hyrax/ability.rb
  app/models/concerns/hyrax/ability/resource_ability.rb
  spec/abilities/file_set_abilities_spec.rb
  spec/abilities/permission_template_ability_spec.rb
Labels: notes-valkyrie, notes-bugfix

#6504 Valkyrization: Fix failing tests in `homepage_spec.rb`
  spec/features/homepage_spec.rb
Labels: valkyrization, notes-valkyrie

#6508 Adapt permission_template_form_spec for valkyire
  spec/forms/hyrax/forms/permission_template_form_spec.rb
Labels: notes-valkyrie, notes-tests

#6509 Adapt misc controller specs for valkyrie
  spec/controllers/hyrax/api/zotero_controller_spec.rb
  spec/controllers/hyrax/batch_uploads_controller_spec.rb
  spec/controllers/hyrax/dashboard/profiles_controller_spec.rb
  spec/controllers/hyrax/fixity_checks_controller_spec.rb
  spec/controllers/hyrax/homepage_controller_spec.rb
  spec/controllers/hyrax/my/highlights_controller_spec.rb
Labels: notes-valkyrie, notes-tests

#6505 Remove leftover collection model setter causing flakes
  spec/abilities/collection_ability_spec.rb
Labels: notes-tests

#6515 Use the catalog's facet_limit partial
  app/views/hyrax/my/facet.html.erb
  spec/views/hyrax/my/facet.html.erb_spec.rb
Labels: notes-bugfix

#6506 Valkyrization: Fix failing tests in `solr_query_builder_service_spec.rb`
  spec/services/hyrax/solr_query_builder_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6511 Valkyrization: Fix failing tests in `work_create_spec.rb`
  spec/hyrax/transactions/work_create_spec.rb
Labels: valkyrization, notes-valkyrie

#6512 Marks test suite as ActiveFedora-only since class is marked for deprecation.
  spec/services/hyrax/derivative_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6514 Adds active_fedora tag to AF-specific tests in spec/helpers/hyrax/embargo_helper_spec.rb.
  spec/helpers/hyrax/embargo_helper_spec.rb
Labels: valkyrization, notes-valkyrie

#6516 Adds active_fedora tag to AF-specific tests in collection_member_search_builder_spec and refactors.
  spec/search_builders/hyrax/collection_member_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6522 Adds work class swapping to spec/services/hyrax/workflow/pending_review_notification_spec.rb.
  spec/services/hyrax/workflow/pending_review_notification_spec.rb
Labels: valkyrization, notes-valkyrie

#6524 Add change_depositor step to fix valkyrie batch deposit as a proxy depositor
  app/jobs/create_work_job.rb
Labels: notes-valkyrie, notes-bugfix

#6527 Valkyrizes `spec/services/hyrax/collections_service_spec.rb`.
  spec/services/hyrax/collections_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6529 Marks the right form ActiveFedora only.
  spec/forms/hyrax/forms/file_set_edit_form_spec.rb
  spec/forms/hyrax/forms/file_set_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6530 Fix save button remaining inactive after upload completes (with passive deposit agreements)
  app/assets/javascripts/hyrax/save_work/uploaded_files.es6
  spec/features/deposit_agreements_spec.rb
Labels: notes-bugfix

#6531 Valkyrizes `spec/services/hyrax/custom_queries/navigators/parent_collections_navigator_spec.rb`.
  spec/services/hyrax/custom_queries/navigators/parent_collections_navigator_spec.rb
Labels: valkyrization, notes-valkyrie

#6532 Valkyrization: Fix failing tests in browse_catalog_spec.rb
  spec/features/browse_catalog_spec.rb
Labels: valkyrization, notes-valkyrie

#6533 Addresses Postgres' further date/time parsing (`spec/hyrax/transactions/apply_change_set_spec.rb`).
  spec/hyrax/transactions/apply_change_set_spec.rb
Labels: valkyrization, notes-valkyrie

#6528 Valkyrizes `spec/services/hyrax/statistics/depositors/summary_spec.rb`.
  spec/services/hyrax/statistics/depositors/summary_spec.rb
Labels: valkyrization, notes-valkyrie

#6539 Adds fileset class swapping and refactoring to `spec/models/checksum_audit_log_spec.rb`.
  spec/models/checksum_audit_log_spec.rb
Labels: valkyrization, notes-valkyrie

#6541 Adds active_fedora tag to AF-specific tests in `spec/hyrax/transactions/steps/set_default_admin_set_spec.rb`.
  spec/hyrax/transactions/steps/set_default_admin_set_spec.rb
Labels: valkyrization, notes-valkyrie

#6543 Tweaks `spec/forms/hyrax/forms/resource_form_spec.rb` to play nice with Enumerators.
  spec/forms/hyrax/forms/resource_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6544 Moves test that checks AF objects with Valkyrie Ids, then Valkyrizes it in original location.
  spec/services/hyrax/custom_queries/navigators/child_works_navigator_spec.rb
  spec/wings/services/custom_queries/navigators/child_works_navigator_spec.rb
Labels: valkyrization, notes-valkyrie

#6545 Fixes `spec/services/hyrax/simple_schema_loader_spec.rb` by copying over sample_metadata.yaml.
  .koppie/config/metadata/sample_metadata.yaml
Labels: valkyrization, notes-valkyrie

#6546 Marks `spec/views/hyrax/batch_uploads/_form.html.erb_spec.rb` as ActiveFedora-only.
  spec/views/hyrax/batch_uploads/_form.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6548 Adds work class swapping and refactoring to `spec/views/shared/select_work_type_modal.html.erb_spec.rb`.
  spec/views/shared/select_work_type_modal.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie
