Repository samvera/hyrax, pull requests merged in 2023-08, with the labels that each got.

#6127 6126 deactivated leases
  app/actors/hyrax/actors/base_actor.rb
  app/actors/hyrax/actors/lease_actor.rb
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/forms/hyrax/forms/work_lease_form.rb
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/indexers/hyrax/valkyrie_work_indexer.rb
  app/models/hyrax/resource.rb
  app/services/hyrax/embargo_manager.rb
  app/services/hyrax/lease_manager.rb
  app/views/hyrax/base/_form_permission_lease.html.erb
  app/views/hyrax/base/_form_visibility_component.html.erb
  lib/hyrax/transactions/steps/add_file_sets.rb
  lib/hyrax/transactions/steps/save.rb
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
  lib/wings/valkyrie/persister.rb
  spec/actors/hyrax/actors/collections_membership_actor_spec.rb
  spec/actors/hyrax/actors/interpret_visibility_actor_spec.rb
  spec/actors/hyrax/actors/lease_actor_spec.rb
  spec/controllers/hyrax/generic_works_controller_json_spec.rb
  spec/factories/hyrax_lease.rb
  spec/factories/hyrax_resource.rb
  spec/features/lease_spec.rb
  spec/indexers/hyrax/valkyrie_file_set_indexer_spec.rb
  spec/models/hyrax/resource_spec.rb
  spec/services/hyrax/admin_set_create_service_spec.rb
  spec/services/hyrax/lease_manager_spec.rb
  spec/wings/active_fedora_converter_spec.rb
Labels: valk-rc

#6114 5844 embargo specs
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/services/hyrax/embargo_manager.rb
  app/views/hyrax/base/_form_permission_embargo.html.erb
  lib/hyrax/transactions/steps/add_file_sets.rb
  lib/wings/active_fedora_converter.rb
  lib/wings/model_transformer.rb
  spec/actors/hyrax/actors/embargo_actor_spec.rb
  spec/actors/hyrax/actors/interpret_visibility_actor_spec.rb
  spec/factories/hyrax_embargo.rb
  spec/features/actor_stack_spec.rb
  spec/features/embargo_spec.rb
  spec/features/work_show_spec.rb
  spec/forms/hyrax/forms/resource_form_spec.rb
  spec/indexers/hyrax/valkyrie_file_set_indexer_spec.rb
  spec/models/hyrax/resource_spec.rb
  spec/requests/riiif_spec.rb
  spec/services/hyrax/embargo_manager_spec.rb
  spec/wings/model_transformer_spec.rb
Labels: valk-rc

#6110 extracted text for valkyrie and wings
  .dassie/db/schema.rb
  app/indexers/hyrax/file_set_indexer.rb
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/jobs/valkyrie_ingest_job.rb
  app/models/concerns/hyrax/file_set/derivatives.rb
  app/models/hyrax/file_metadata.rb
  app/services/hyrax/custom_queries/find_file_metadata.rb
  app/services/hyrax/derivative_path.rb
  app/services/hyrax/file_set_derivatives_service.rb
  app/services/hyrax/persist_directly_contained_output_file_service.rb
  app/services/hyrax/valkyrie_persist_derivatives.rb
  app/services/hyrax/valkyrie_upload.rb
  app/services/hyrax/versioning_service.rb
  lib/wings/active_fedora_converter.rb
  lib/wings/active_fedora_converter/default_work.rb
  lib/wings/active_fedora_converter/file_metadata_node.rb
  lib/wings/model_transformer.rb
  lib/wings/setup.rb
  spec/factories/hyrax_file_metadata.rb
  spec/indexers/hyrax/valkyrie_file_set_indexer_spec.rb
  spec/jobs/create_derivatives_job_spec.rb
  spec/jobs/valkyrie_ingest_job_spec.rb
  spec/models/hyrax/file_metadata_spec.rb
  spec/services/hyrax/characterization/file_set_description_spec.rb
  spec/services/hyrax/custom_queries/find_file_metadata_spec.rb
  spec/services/hyrax/listeners/file_metadata_listener_spec.rb
  spec/wings/active_fedora_converter_spec.rb
  spec/wings/hydra/works/services/add_file_to_file_set_spec.rb
  spec/wings/services/custom_queries/find_file_metadata_spec.rb
  spec/wings/valkyrie/persister_spec.rb
  spec/wings/valkyrie/storage_spec.rb
Labels: valk-rc

#6152 Fix IIIF manifests when the presenter model is a SolrDocument
  app/presenters/hyrax/iiif_manifest_presenter.rb
Labels: notes-valkyrie

#6150 wings: bootstrap DefaultWork with CoreMetadata
  lib/wings/active_fedora_converter/default_work.rb
Labels: wings, notes-bugfix

#6144 remove fallback behavior for dropped InitializeWorkflowActor
  app/services/hyrax/listeners/workflow_listener.rb
Labels: notes-major

#6169 skip ActiveFedora specs if `disable_wings` is on
  spec/spec_helper.rb
  spec/wings/active_fedora_converter_spec.rb
  spec/wings/attribute_transformer_spec.rb
  spec/wings/hydra/works/services/add_file_to_file_set_spec.rb
  spec/wings/model_transformer_spec.rb
  spec/wings/orm_converter_spec.rb
  spec/wings/services/custom_queries/find_access_control_spec.rb
  spec/wings/services/custom_queries/find_collections_by_type_spec.rb
  spec/wings/services/custom_queries/find_file_metadata_spec.rb
  spec/wings/services/custom_queries/find_many_by_alternate_ids_spec.rb
  spec/wings/transformer_value_mapper_spec.rb
  spec/wings/valkyrie/persister_spec.rb
  spec/wings/valkyrie/query_service_spec.rb
  spec/wings/valkyrie/resource_factory_spec.rb
  spec/wings/valkyrie/storage_spec.rb
Labels: test coverage, notes-valkyrie

#6167 [semver-major] rename object.file.updated to file.updated
  app/services/hyrax/listeners/file_metadata_listener.rb
  app/services/hyrax/valkyrie_upload.rb
  lib/hyrax/publisher.rb
  spec/services/hyrax/valkyrie_upload_spec.rb
Labels: valkyrization, notes-major

#6202 don't run AF Works::MigrationService specs if `disable_wings`
  spec/services/hyrax/works/migration_service_spec.rb
Labels: test coverage, notes-valkyrie

#6191 disable `spec/wings_spec.rb` when `disable_wings` is true
  spec/wings_spec.rb
Labels: test coverage, notes-valkyrie

#6199 refactor ChangeDepositorService specs to use valkyrie for setup
  spec/services/hyrax/change_depositor_service_spec.rb
Labels: test coverage, notes-valkyrie

#6174 test Ruby 3.2 with docker/dassie
  .circleci/config.yml
  .dassie/config/environments/test.rb
  .dockerignore
  .koppie/config/environments/test.rb
  lib/hyrax.rb
Labels: test coverage

#6188 disable generated Controller specs for AF models if `disable_wings`
  spec/controllers/hyrax/generic_works_controller_json_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
Labels: test coverage, notes-valkyrie

#6185 skip AF model specs when disable_wings is flagged
  spec/models/admin_set_spec.rb
  spec/models/collection_spec.rb
  spec/models/file_set_spec.rb
  spec/models/generic_work_spec.rb
Labels: test coverage, valkyrization

#6173 refactor CollectionMemberService specs to use Valkyrie for setup
  spec/services/hyrax/collection_member_service_spec.rb
Labels: test coverage, notes-valkyrie

#6214 don't test AF path in `InheritPermissionsJob` when `disable_wings`
  spec/jobs/inherit_permissions_job_spec.rb
Labels: test coverage, notes-valkyrie

#6213 disable `AttachFilesToWorkJob` specs if `disable_wings`
  spec/jobs/attach_files_to_work_job_spec.rb
Labels: test coverage, notes-valkyrie

#6215 don't test AF path in `FileSetAttachedEventJob` when `disable_wings`
  spec/jobs/file_set_attached_event_job_spec.rb
Labels: test coverage, notes-valkyrie

#6183 [semver-major] drop support for Ruby before 3.2
  .circleci/config.yml
  .dassie/db/schema.rb
  app/services/hyrax/visibility_intention.rb
  app/services/hyrax/workflow/grant_edit_to_depositor.rb
  app/services/hyrax/workflow/grant_read_to_depositor.rb
  documentation/developing-your-hyrax-based-app.md
  hyrax.gemspec
Labels: notes-major

#6216 skip `MembersPermissionJobBehavior` AF tests when `disable_wings`
  spec/jobs/hyrax/grant_edit_to_members_job_spec.rb
  spec/jobs/hyrax/grant_read_to_members_job_spec.rb
  spec/jobs/hyrax/revoke_edit_from_members_job_spec.rb
Labels: test coverage, notes-valkyrie

#6159 Set geonames usernames using environment variable
  .dassie/config/initializers/hyrax.rb
  .koppie/config/initializers/hyrax.rb
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
Labels: notes-minor

#6217 Fix file manager sorting for Koppie
  app/assets/javascripts/hyrax/file_manager/sorting.es6
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/forms/hyrax/forms/file_manager_form.rb
  app/presenters/hyrax/work_show_presenter.rb
  app/views/hyrax/base/_file_manager_members.html.erb
  app/views/hyrax/base/file_manager.html.erb
  app/views/hyrax/base/show.json.jbuilder
  spec/features/file_manager_spec.rb
  spec/forms/hyrax/forms/file_manager_form_spec.rb
  spec/views/hyrax/base/file_manager.html.erb_spec.rb
Labels: notes-major

#6210 Run javascript specs on remote browser
  .circleci/config.yml
  .dassie/.env
  .dockerignore
  .koppie/.env
  karma.conf.js
  package.json
  spec/javascripts/jasmine_spec.rb
Labels: notes-minor

#6200 disable AF integration specs for ThumbnailPathService if `disable_wings`
  spec/services/hyrax/thumbnail_path_service_spec.rb
Labels: test coverage, notes-valkyrie

#6212 Reindex the work during derivative creation if it is the work's thumbnail
  .koppie/config/initializers/hyrax.rb
  app/jobs/valkyrie_create_derivatives_job.rb
  spec/jobs/valkyrie_create_derivatives_job_spec.rb
Labels: notes-bugfix

#6228 Add postgresql port helm chart helper template
  chart/hyrax/Chart.yaml
  chart/hyrax/templates/_helpers.tpl
  chart/hyrax/templates/configmap-env.yaml
  chart/hyrax/values.yaml
Labels: notes-container

#6238 use locally defined conf to map mime_types derivative methods
  app/services/hyrax/file_set_derivatives_service.rb
  lib/hyrax/configuration.rb
  spec/factories/hyrax_file_metadata.rb
  spec/services/hyrax/file_set_derivatives_service_spec.rb
Labels: notes-minor, notes-valkyrie

#6233 use Valkyrie for test setup on SolrQueryService specs
  spec/services/hyrax/solr_query_service_spec.rb
Labels: test coverage, notes-valkyrie

#6240 use Valkyrie to setup AdminSetService specs
  spec/factories/administrative_sets.rb
  spec/services/hyrax/admin_set_service_spec.rb
Labels: test coverage, notes-valkyrie

#6243 mark generic_work_abilities_spec ActiveFedora only
  spec/abilities/generic_work_abilities_spec.rb
Labels: notes-valkyrie

#6246 mark GenericWorkIndexer specs as ActiveFedora only
  spec/indexers/hyrax/generic_work_indexer_spec.rb
Labels: notes-valkyrie

#6247 mark Hyrax Callbacks tests as :active_fedora
  spec/config/hyrax_events_spec.rb
Labels: notes-valkyrie

#6245 mark JobIoWrapper specs as ActiveFedora only
  spec/models/job_io_wrapper_spec.rb
Labels: notes-valkyrie

#6244 make SingleUseLinksController use valkyrie for spec setup
  spec/controllers/hyrax/single_use_links_controller_spec.rb
Labels: notes-valkyrie

#6239 Add method to VersioningService to detect support
  app/services/hyrax/versioning_service.rb
  spec/services/hyrax/versioning_service_spec.rb
Labels: notes-minor, notes-valkyrie

#6251 use Valkyrie for setup on PermissionTemplateApplicator
  spec/services/hyrax/permission_template_applicator_spec.rb
Labels: notes-valkyrie

#6256 never set `metadata/storage_adapter` to wings or AF if disable_wings
  lib/wings/setup.rb
  spec/wings_helper.rb
Labels: wings, notes-valkyrie, notes-tests

#6263 don't test legacy CharacterizeJob in `.koppie`
  spec/jobs/characterize_job_spec.rb
Labels: notes-valkyrie, notes-tests

#6264 don't test ActiveFedora specific VersioningService tests on `.koppie`
  spec/services/hyrax/versioning_service_spec.rb
Labels: notes-valkyrie, notes-tests

#6258 skip more Wings specs
  spec/spec_helper.rb
  spec/wings/valkyrie/metadata_adapter_spec.rb
Labels: notes-valkyrie, notes-tests

#6261 only use specialized `Wings::WorkSearchBuilder` if Wings is enabled
  spec/controllers/concerns/hyrax/works_controller_behavior_spec.rb
Labels: notes-valkyrie, notes-tests

#6270 Use updated fitsservlet image
  docker-compose-koppie.yml
  docker-compose.yml
Labels: notes-container

#6259 test behavior after a published Fixity check failure on Valkyrie
  app/services/hyrax/fixity_check_failure_service.rb
  spec/factories/hyrax_file_metadata.rb
  spec/services/hyrax/fixity_check_failure_service_spec.rb
  spec/services/hyrax/listeners/file_set_lifecycle_notification_listener_spec.rb
Labels: notes-valkyrie, notes-bugfix

#6271 chart: use fits chart 0.2.0
  chart/hyrax/Chart.yaml
Labels: notes-container

#6272 remove Hyrax::RoleManagement from `.koppie`
  .koppie/Gemfile
  .koppie/app/models/ability.rb
  .koppie/app/models/user.rb
  .koppie/config/role_map.yml
  .koppie/config/routes.rb
Labels: notes-valkyrie, notes-container

#6275 update UserProfilePresenter to use Valkyrie setup
  spec/presenters/hyrax/user_profile_presenter_spec.rb
Labels: notes-valkyrie, notes-tests

#6274 use Valkyrie for test setup on Collections:PremissionsService specs
  spec/services/hyrax/collections/permissions_service_spec.rb
Labels: notes-valkyrie, notes-tests

#6282 mark AF tests for PropagateChangeDepositorJob as `:active_fedora`
  spec/jobs/hyrax/propagate_change_depositor_job_spec.rb
Labels: notes-valkyrie, notes-tests

#6268 fixes all but one of the test errors for collection type
  spec/features/collection_type_spec.rb
Labels: notes-valkyrie, notes-tests

#6279 make ResourceVisibilityPropagator use Valkyrie for setup
  spec/factories/hyrax_work.rb
  spec/services/hyrax/resource_visibility_propagator_spec.rb
Labels: notes-valkyrie, notes-tests
