Repository samvera/hyrax, pull requests merged in 2023-10, with the labels that each got.

#6341 Fix lease/embargo controller and specs in koppie
  app/controllers/concerns/hyrax/embargoes_controller_behavior.rb
  app/controllers/concerns/hyrax/leases_controller_behavior.rb
  spec/controllers/hyrax/embargoes_controller_spec.rb
  spec/controllers/hyrax/leases_controller_spec.rb
  spec/factories/hyrax_file_set.rb
  spec/factories/hyrax_work.rb
Labels: notes-valkyrie, notes-tests

#6338 Adds a permissive schema to the Fedora Valkyrie adapter (#6332).
  .dassie/config/metadata/collection_resource.yaml
  .dassie/config/metadata/monograph.yaml
  .dassie/config/metadata/sample_metadata.yaml
  .koppie/config/initializers/1_valkyrie.rb
  .koppie/config/metadata/collection_resource.yaml
  .koppie/config/metadata/generic_work.yaml
  .koppie/config/metadata/monograph.yaml
  app/services/hyrax/simple_schema_loader.rb
  config/metadata/basic_metadata.yaml
  config/metadata/core_metadata.yaml
  config/metadata/file_set_metadata.yaml
  config/metadata/hyrax_internal_metadata.yaml
  lib/generators/hyrax/collection_resource/templates/collection_metadata.yaml
  lib/generators/hyrax/work_resource/templates/metadata.yaml
  spec/services/hyrax/simple_schema_loader_spec.rb
Labels: notes-valkyrie

#6347 Koppie: Short circuit specs loading of wings files
  spec/actors/hyrax/actors/file_actor_spec.rb
  spec/actors/hyrax/actors/generic_work_actor_spec.rb
  spec/forms/hyrax/generic_work_form_spec.rb
  spec/wings/active_fedora_converter_spec.rb
  spec/wings/attribute_transformer_spec.rb
  spec/wings/converter_value_mapper_spec.rb
  spec/wings/hydra/works/services/add_file_to_file_set_spec.rb
  spec/wings/model_transformer_spec.rb
  spec/wings/orm_converter_spec.rb
  spec/wings/services/custom_queries/find_access_control_spec.rb
  spec/wings/services/custom_queries/find_collections_by_type_spec.rb
  spec/wings/services/custom_queries/find_file_metadata_spec.rb
  spec/wings/services/custom_queries/find_ids_by_model_spec.rb
  spec/wings/services/custom_queries/find_many_by_alternate_ids_spec.rb
  spec/wings/transformer_value_mapper_spec.rb
  spec/wings/valkyrie/metadata_adapter_spec.rb
  spec/wings/valkyrie/persister_spec.rb
  spec/wings/valkyrie/query_service_spec.rb
  spec/wings/valkyrie/resource_factory_spec.rb
  spec/wings/valkyrie/storage_spec.rb
  spec/wings_spec.rb
Labels: notes-tests

#6348 Fix collection view specs for koppie
  spec/views/collections/edit_fields/_based_near.html.erb_spec.rb
  spec/views/hyrax/collections/_show_document_list_row.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_form.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_form_discovery.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_list_collections.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_show_document_list_row.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/edit.html.erb_spec.rb
Labels: notes-tests

#6345 Pass our ch12n config to the ch12n service and enable fits_servlet
  .dassie/.env
  .koppie/.env
  app/services/hyrax/listeners/file_metadata_listener.rb
Labels: notes-valkyrie

#6343 Fix valk specs and mark AF specs
  spec/jobs/visibility_copy_job_spec.rb
Labels: notes-tests

#6344 Fix Valkyrie base view specs
  app/views/hyrax/base/show.json.jbuilder
  lib/hyrax/resource_name.rb
  spec/hyrax/resource_name_spec.rb
  spec/views/hyrax/base/_currently_shared.html.erb_spec.rb
  spec/views/hyrax/base/_form_files.html.erb_spec.rb
  spec/views/hyrax/base/_form_metadata.html.erb_spec.rb
  spec/views/hyrax/base/_form_progress.html.erb_spec.rb
  spec/views/hyrax/base/_form_rendering.html.erb_spec.rb
  spec/views/hyrax/base/_form_share.erb_spec.rb
  spec/views/hyrax/base/edit.html.erb_spec.rb
  spec/views/hyrax/base/show.html.erb_spec.rb
  spec/views/hyrax/base/show.json.jbuilder_spec.rb
Labels: notes-valkyrie

#6350 Remove deprecated .create_default_admin_set method
  app/services/hyrax/admin_set_create_service.rb
  spec/services/hyrax/admin_set_create_service_spec.rb
Labels: notes-deprecation

#6355 Make fileset representative_id and thumbnail_id readonly in form
  app/forms/hyrax/forms/file_set_form.rb
  app/models/hyrax/file_set.rb
Labels: notes-valkyrie

#6356 Provide default for characterization_options
  lib/hyrax/configuration.rb
Labels: notes-bugfix

#6358 Fix sirenia fcrepo volume location
  docker-compose-sirenia.yml
Labels: notes-container

#6367 Fixes the deletion of collections 500 (#6362).
  app/controllers/hyrax/batch_edits_controller.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/services/hyrax/listeners/member_cleanup_listener.rb
  lib/hyrax/transactions/collection_destroy.rb
  lib/hyrax/transactions/container.rb
  lib/hyrax/transactions/steps/remove_from_membership.rb
  spec/hyrax/transactions/collection_destroy_spec.rb
  spec/hyrax/transactions/steps/remove_from_membership_spec.rb
  spec/services/hyrax/listeners/member_cleanup_listener_spec.rb
Labels: bug, valkyrie-fedora

#6368 Use a hashed version identifier in IIIF manifest
  .dassie/config/initializers/riiif.rb
  .koppie/config/initializers/riiif.rb
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/controllers/hyrax/file_sets_controller.rb
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/models/concerns/hyrax/riiif_file.rb
  app/models/hyrax/file_set.rb
  app/services/hyrax/riiif_file_resolver.rb
  config/initializers/file_length_patch.rb
  hyrax.gemspec
  lib/generators/hyrax/templates/config/initializers/riiif.rb
  lib/hyrax/specs/shared_specs/hydra_works.rb
  lib/hyrax/transactions/steps/file_metadata_delete.rb
  spec/factories/hyrax_file_metadata.rb
  spec/presenters/hyrax/file_set_presenter_spec.rb
  spec/services/hyrax/riiif_file_resolver_spec.rb
  spec/spec_helper.rb
Labels: notes-minor, notes-valkyrie

#6371 Fixes the swapping of Thumbnail and Rep. Media per work (#6361).
  app/assets/javascripts/hyrax/file_manager/member.es6
  app/views/hyrax/base/_file_manager_resource_form.html.erb
Labels: bug, backport needed, valkyrization

#6372 Fix valkyrie resource json response
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  spec/controllers/concerns/hyrax/works_controller_behavior_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
Labels: notes-valkyrie

#6375 Remove deprecated `available_child_collections` and `available_parent_collections`
  app/forms/hyrax/forms/collection_form.rb
  app/forms/hyrax/forms/dashboard/nest_collection_form.rb
  app/presenters/hyrax/collection_presenter.rb
  spec/forms/hyrax/forms/dashboard/nest_collection_form_spec.rb
Labels: notes-deprecation

#6374 Deprecate use of ActiveFedora and Wings
  lib/wings.rb
Labels: notes-deprecation

#6376 Remove deprecated `reset_access_controls!`
  app/forms/hyrax/forms/permission_template_form.rb
  spec/forms/hyrax/forms/permission_template_form_spec.rb
  spec/models/collection_spec.rb
Labels: notes-deprecation

#6377 Remove deprecated `Collection#collection_type`
  app/models/concerns/hyrax/collection_behavior.rb
  spec/models/collection_spec.rb
Labels: notes-deprecation

#6379 Prep 5.0.0.rc2
  CONTAINERS.md
  documentation/developing-your-hyrax-based-app.md
  lib/hyrax/version.rb
  template.rb
Labels: notes-docs

#6384 Fix flaky spec by not redefining File and YAML responses
  spec/strategies/hyrax/strategies/yaml_strategy_spec.rb
Labels: notes-tests

#6380 Fix loading outdated FileSet causing flakiness
  spec/wings/model_transformer_spec.rb
Labels: notes-tests

#6381 Fix user links menu running off right side of page
  app/views/_user_util_links.html.erb
Labels: notes-bugfix

#6388 disable `work_form_spec` when AF is disabled
  spec/forms/hyrax/forms/work_form_spec.rb
Labels: notes-valkyrie, notes-tests

#6398 Fix instance variable used for admin set form
  lib/hyrax/configuration.rb
Labels: bug

#6400 deprecate `Statistics::QueryService`
  app/services/hyrax/statistics/query_service.rb
  spec/services/hyrax/statistics/query_service_spec.rb
Labels: notes-deprecation

#6403 Updates the works in proxies and abilities spec to valkyrie.
  spec/abilities/proxies_and_transfer_abilities_spec.rb
Labels: valkyrization, notes-valkyrie

#6399 Clarify purpose of FileSetFileService
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/presenters/hyrax/version_list_presenter.rb
  app/services/hyrax/file_set_file_service.rb
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
  lib/hyrax/configuration.rb
  spec/lib/hyrax/configuration_spec.rb
  spec/services/hyrax/file_set_file_service_spec.rb
Labels: notes-minor, notes-valkyrie
