Repository samvera/hyrax, pull requests merged in 2023-09, with the labels that each got.

#6287 disable AF only specs for `Hyrax::ChildTypes`
  spec/services/hyrax/child_types_spec.rb
Labels: notes-valkyrie, notes-tests

#6284 Fix rubocop errors and add rubocop job to CircleCI config
  .circleci/config.yml
  app/presenters/hyrax/version_list_presenter.rb
  spec/controllers/hyrax/my/collections_controller_spec.rb
  spec/factories/administrative_sets.rb
  spec/services/hyrax/collections/permissions_service_spec.rb
Labels: notes-tests

#6187 skip Wings specific `SolrDocumentBehavior` tests if `disable_wings`
  spec/models/concerns/hyrax/solr_document_behavior_spec.rb
Labels: test coverage, notes-valkyrie

#6298 Wings reflections handling
  lib/wings/attribute_transformer.rb
  lib/wings/model_transformer.rb
  lib/wings/orm_converter.rb
  spec/wings/model_transformer_spec.rb
Labels: wings, notes-bugfix

#6299 do not fall back to generic resourceform if there is a syntax error
  app/forms/hyrax/forms/resource_form.rb
Labels: notes-bugfix

#6313 bump dry logic to a version that is ruby 3.x compatibile
  hyrax.gemspec
  lib/hyrax/transactions/container.rb
Labels: notes-bugfix

#6242 update CollectionType GlobalID update task to use valkyrie
  app/models/concerns/hyrax/collection_behavior.rb
  lib/tasks/collection_type_global_id.rake
  spec/tasks/rake_spec.rb
Labels: notes-valkyrie

#6315 Bump min rails version to 6.1 and align dassie/koppie gems
  .dassie/Gemfile
  .koppie/Gemfile
  .koppie/Rakefile
  hyrax.gemspec
Labels: notes-major

#6317 Enable access of form classes, not just instances
  app/forms/hyrax/forms/pcdm_object_form.rb
  app/forms/hyrax/forms/resource_form.rb
  lib/generators/hyrax/work_resource/templates/form.rb.erb
Labels: notes-minor

#6318 Fix kaniko builds of forked PRs
  .circleci/config.yml
Labels: notes-tests

#6252 make `Hyrax::Identifier::Dispatcher` support Valkryie
  app/services/hyrax/identifier/dispatcher.rb
  spec/services/hyrax/identifier/dispatcher_spec.rb
Labels: notes-valkyrie

#6300 make valkyrie solr adapter take full url argument
  lib/valkyrie/indexing/solr/indexing_adapter.rb
Labels: notes-bugfix

#6325 dassie/koppie alignment and added bundle caching
  .dassie/.env
  .dassie/config/redis.yml
  .koppie/.env
  .koppie/config/application.rb
  bin/dev-entrypoint.sh
  docker-compose-koppie.yml
  docker-compose.yml
Labels: notes-container

#6255 disable WorkFormService specs in .koppie
  app/controllers/hyrax/batch_uploads_controller.rb
  spec/services/hyrax/work_form_service_spec.rb
Labels: notes-valkyrie, notes-tests

#6285 port most FileSetPresenter specs to Valkyrie
  app/models/hyrax/file_set.rb
  app/services/hyrax/valkyrie_upload.rb
  lib/hyrax/specs/shared_specs/hydra_works.rb
  lib/wings/active_fedora_converter.rb
  spec/factories/hyrax_file_metadata.rb
  spec/factories/hyrax_file_set.rb
  spec/factories/uploaded_files.rb
  spec/indexers/hyrax/valkyrie_file_set_indexer_spec.rb
  spec/presenters/hyrax/file_set_presenter_spec.rb
  spec/wings/active_fedora_converter_spec.rb
  spec/wings/model_transformer_spec.rb
Labels: notes-minor, notes-valkyrie, notes-tests

#6322 Redis current is depericated, replace in a similar manner to other gems
  app/services/hyrax/lock_manager.rb
  lib/hyrax/redis_event_store.rb
  spec/lib/hyrax/redis_event_store_spec.rb
Labels: notes-minor

#6329 Valkyrie Fedora metadata/storage adapter compatibility
  app/models/hyrax/file_metadata.rb
  app/models/hyrax/work.rb
  app/services/hyrax/collections/collection_member_service.rb
  app/services/hyrax/valkyrie_upload.rb
  app/services/hyrax/work_uploads_handler.rb
  app/validators/hyrax/collection_membership_validator.rb
  config/initializers/file_length_patch.rb
  lib/hyrax/configuration.rb
  lib/hyrax/transactions/steps/add_to_parent.rb
Labels: notes-minor

#6331 Add config for valkyrie fedora and "sirenia" compose file
  .koppie/.env
  .koppie/config/initializers/1_valkyrie.rb
  docker-compose-sirenia.yml
Labels: notes-valkyrie
