Repository samvera/hyrax, pull requests merged in 2023-11, with the labels that each got.

#6409 Turns off AF testing in koppie testing for nested_collections_search_builder_spec.
  spec/search_builders/hyrax/dashboard/nested_collections_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6408 Fix collection sort by drop down
  app/services/hyrax/collections/collection_member_search_service.rb
Labels: notes-bugfix

#6411 Attempts to fix the failing specs for shares_controller_spec.
  spec/controllers/hyrax/my/shares_controller_spec.rb
Labels: notes-valkyrie

#6397 Added 'generator' meta-tag to main layout 'head' partial
  .gitignore
  app/views/layouts/_head_tag_content.html.erb
Labels: notes-minor

#6412 Valkyrize collection feature spec
  app/controllers/concerns/hyrax/collections_controller_behavior.rb
  spec/features/collection_spec.rb
Labels: notes-valkyrie, notes-bugfix

#6420 Updates tests where mock_model errs.
  spec/models/file_view_stat_spec.rb
  spec/models/work_view_stat_spec.rb
Labels: valkyrization, notes-valkyrie

#6418 Updates select_type_presenter_spec.rb for both valkyrie and AF.
  spec/presenters/hyrax/select_type_presenter_spec.rb
Labels: valkyrization, notes-valkyrie

#6416 Updates create_work_spec for both valkyrie and AF.
  spec/features/create_work_spec.rb
Labels: valkyrization, notes-valkyrie

#6422 Fixes more mock model complications
  spec/models/file_download_stat_spec.rb
  spec/presenters/hyrax/admin_set_presenter_spec.rb
Labels: valkyrization, notes-valkyrie

#6425 Last batch of mock_model rspec fixes.
  app/services/hyrax/custom_queries/find_file_metadata.rb
  spec/lib/hyrax/arkivo/actor_spec.rb
  spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6434 Adds :active_fedora tag to batch_upload_form_spec.
  spec/forms/hyrax/forms/batch_upload_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6432 Adds :active_fedora tag to revoke_edit_job_spec for AF-specific test.
  spec/jobs/hyrax/revoke_edit_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6431 Adds :active_fedora tag to change_content_depositor_service_spec again.
  spec/services/hyrax/change_content_depositor_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6430 Refactors collection_presenter_spec to cleanly split AF and Valkyrie testing.
  spec/presenters/hyrax/collection_presenter_spec.rb
  spec/support/shared_examples_for_collection_presenter.rb
Labels: valkyrization, notes-valkyrie

#6429 Fix ownership_transfer_spec.rb tests for Valkyrie
  spec/features/ownership_transfer_spec.rb
Labels: valkyrization, notes-valkyrie

#6433 Refactors _subject.html.erb_spec.rb to cleanly split AF and Valkyrie testing.
  spec/views/records/edit_fields/_subject.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6428 Updates create_child_work_spec.rb for valkyrie.
  spec/features/create_child_work_spec.rb
Labels: valkyrization, notes-valkyrie

#6427 ♻️ Extract Hyrax::GroupBehavior
  app/models/hyrax/group.rb
  app/models/hyrax/group_behavior.rb
Labels: notes-minor

#6438 Adapt more record view specs for valkyrie
  spec/views/records/edit_fields/_description.html.erb_spec.rb
  spec/views/records/edit_fields/_language.html.erb_spec.rb
  spec/views/records/edit_fields/_subject.html.erb_spec.rb
Labels: notes-valkyrie, notes-tests

#6437 Switch to Capybara's animation disabler
  .dassie/config/environments/test.rb
  lib/hyrax/specs/capybara.rb
  lib/hyrax/specs/disable_animations_in_test_environment.rb
Labels: notes-tests

#6426 Fix trophies_controller_spec.rb tests for Valkyrie
  spec/controllers/hyrax/trophies_controller_spec.rb
Labels: valkyrization, notes-valkyrie

#6439 Collection Location field fixes; Valkyrize collection dashboard feature spec
  .koppie/app/forms/collection_resource_form.rb
  .koppie/app/indexers/collection_resource_indexer.rb
  .koppie/app/models/collection_resource.rb
  .koppie/config/metadata/collection_resource.yaml
  app/controllers/hyrax/my/collections_controller.rb
  app/forms/concerns/hyrax/basic_metadata_form_fields_behavior.rb
  app/forms/hyrax/forms/collection_form.rb
  app/indexers/hyrax/location_indexer.rb
  app/indexers/hyrax/pcdm_collection_indexer.rb
  app/services/hyrax/location_service.rb
  app/services/hyrax/multiple_membership_checker.rb
  app/views/collections/edit_fields/_based_near.html.erb
  app/views/hyrax/admin/admin_sets/edit.html.erb
  lib/wings/model_registry.rb
  spec/controllers/concerns/hyrax/works_controller_behavior_spec.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/factories/hyrax_collection.rb
  spec/features/collection_multi_membership_spec.rb
  spec/features/collection_spec.rb
  spec/features/dashboard/collection_spec.rb
  spec/forms/hyrax/forms/collection_form_spec.rb
  spec/support/wings_models.rb
  spec/views/collections/edit_fields/_based_near.html.erb_spec.rb
  spec/views/hyrax/dashboard/collections/_form.html.erb_spec.rb
  spec/views/records/edit_fields/_based_near.html.erb_spec.rb
Labels: notes-minor, notes-valkyrie, notes-tests

#6440 Only default admin_set_id when it is unset
  app/forms/hyrax/forms/pcdm_object_form.rb
  spec/features/edit_work_resource_spec.rb
Labels: notes-bugfix

#6444 Valkyrie conversion of collection_members_controller_spec
  spec/controllers/hyrax/dashboard/collection_members_controller_spec.rb
Labels: notes-valkyrie, notes-tests

#6445 Valkyrie conversion of permission_template_accesses_controller_spec.rb
  spec/controllers/hyrax/admin/permission_template_accesses_controller_spec.rb
Labels: notes-valkyrie, notes-tests

#6443 Edit catalog_search_spec.rb for Valkyrie compatibility
  spec/features/catalog_search_spec.rb
Labels: valkyrization, notes-valkyrie

#6448 Updates nest_collection_form_spec with :active_fedora tag.
  spec/forms/hyrax/forms/dashboard/nest_collection_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6450 Valkyrizes spec/authorities/qa/authorities/collections_spec.rb.
  spec/authorities/qa/authorities/collections_spec.rb
Labels: valkyrization, notes-valkyrie

#6447 Valkyrize downloads_controller_spec; Improved Range and Cache-Control features
  app/controllers/concerns/hyrax/local_file_downloads_controller_behavior.rb
  app/controllers/concerns/hyrax/stream_file_downloads_controller_behavior.rb
  app/controllers/concerns/hyrax/valkyrie_downloads_controller_behavior.rb
  app/controllers/hyrax/downloads_controller.rb
  app/models/hyrax/file_metadata.rb
  spec/controllers/hyrax/downloads_controller_spec.rb
  spec/factories/hyrax_file_metadata.rb
Labels: valkyrization, notes-minor, notes-valkyrie

#6454 Valkyrizes spec/abilities/ability_spec.rb.
  spec/abilities/ability_spec.rb
Labels: valkyrization, notes-valkyrie

#6451 Fix content_delete_event_job_spec.rb
  spec/jobs/content_delete_event_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6455 Edit content_deposit_event_job_spec.rb
  spec/jobs/content_deposit_event_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6441 Refactor Valkyrie indexer API (to match forms)
  app/indexers/concerns/hyrax/location_indexer.rb
  app/indexers/concerns/hyrax/permission_indexer.rb
  app/indexers/concerns/hyrax/resource_indexer.rb
  app/indexers/concerns/hyrax/thumbnail_indexer.rb
  app/indexers/concerns/hyrax/visibility_indexer.rb
  app/indexers/hyrax/administrative_set_indexer.rb
  app/indexers/hyrax/indexers/administrative_set_indexer.rb
  app/indexers/hyrax/indexers/file_set_indexer.rb
  app/indexers/hyrax/indexers/pcdm_collection_indexer.rb
  app/indexers/hyrax/indexers/pcdm_object_indexer.rb
  app/indexers/hyrax/indexers/resource_indexer.rb
  app/indexers/hyrax/pcdm_collection_indexer.rb
  app/indexers/hyrax/valkyrie_collection_indexer.rb
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/indexers/hyrax/valkyrie_indexer.rb
  app/indexers/hyrax/valkyrie_work_indexer.rb
  lib/generators/hyrax/collection_resource/templates/collection_indexer.rb.erb
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
  lib/generators/hyrax/work_resource/templates/indexer.rb.erb
  lib/hyrax/configuration.rb
  lib/hyrax/indexer.rb
  lib/valkyrie/indexing/solr/indexing_adapter.rb
  lib/wings/active_fedora_converter/default_work.rb
  lib/wings/active_fedora_converter/file_metadata_node.rb
  spec/indexers/concerns/hyrax/permission_indexer_spec.rb
  spec/indexers/concerns/hyrax/resource_indexer_spec.rb
  spec/indexers/concerns/hyrax/visibility_indexer_spec.rb
  spec/indexers/hyrax/administrative_set_indexer_spec.rb
  spec/indexers/hyrax/indexers/administrative_set_indexer_spec.rb
  spec/indexers/hyrax/indexers/file_set_indexer_spec.rb
  spec/indexers/hyrax/indexers/pcdm_collection_indexer_spec.rb
  spec/indexers/hyrax/indexers/pcdm_object_indexer_spec.rb
  spec/indexers/hyrax/indexers/resource_indexer_spec.rb
  spec/indexers/hyrax/pcdm_collection_indexer_spec.rb
  spec/indexers/hyrax/valkyrie_collection_indexer_spec.rb
  spec/indexers/hyrax/valkyrie_file_set_indexer_spec.rb
  spec/indexers/hyrax/valkyrie_indexer_spec.rb
  spec/indexers/hyrax/valkyrie_work_indexer_spec.rb
  spec/lib/hyrax/configuration_spec.rb
  spec/presenters/hyrax/file_set_presenter_spec.rb
  spec/wings/active_fedora_converter_spec.rb
Labels: notes-major, notes-valkyrie

#6446 Updates iiif_manifest_presenter_spec for Valkyrie.
  spec/presenters/hyrax/iiif_manifest_presenter_spec.rb
Labels: valkyrization, notes-valkyrie

#6457 Valkyrizes spec/models/hyrax/permission_template_spec.rb.
  spec/models/hyrax/permission_template_spec.rb
Labels: valkyrization, notes-valkyrie

#6458 Valkyrizes spec/helpers/hyrax/file_set_helper_spec.rb.
  spec/helpers/hyrax/file_set_helper_spec.rb
Labels: valkyrization, notes-valkyrie

#6462 Fix form/indexer builder configuration
  lib/hyrax/configuration.rb
Labels: bug

#6472 Utilizes Valkyrie patterns for grant_edit_to_depositor_spec.
  spec/services/hyrax/workflow/grant_edit_to_depositor_spec.rb
Labels: valkyrization, notes-valkyrie

#6465 Swaps out Global ID call to Valkyrie-friendly method.
  spec/forms/hyrax/forms/workflow_action_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6453 Updates tested collection objects to Valkyrie-compliant (spec/search_builders/hyrax/collection_search_builder_spec.rb).
  spec/search_builders/hyrax/collection_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6460 Updates find_works_search_builder to allow for both id strings as well as Valkyrie id objects.
  app/search_builders/hyrax/my/find_works_search_builder.rb
  spec/search_builders/hyrax/my/find_works_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6466 Swaps to create so that IDs are minted, allowing queries to perform.
  spec/helpers/hyrax/membership_helper_spec.rb
Labels: valkyrization, notes-valkyrie

#6467 Marks test suite as ActiveFedora-only, since importer has no Valkyrization.
  spec/services/hyrax/user_stat_importer_spec.rb
Labels: valkyrization, notes-valkyrie

#6469 Valkyrization: Fix failing tests in content_update_event_job_spec.rb
  spec/jobs/content_update_event_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6470 Valkyrization: Fix failing tests in content_new_version_event_job_spec.rb
  spec/jobs/content_new_version_event_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6474 Utilizes Valkyrie patterns for collection_types_controller_spec.
  docker-compose-koppie.yml
  spec/controllers/hyrax/admin/collection_types_controller_spec.rb
Labels: valkyrization, notes-valkyrie

#6473 Utilizes Valkyrie patterns for collection_type_spec.
  spec/models/hyrax/collection_type_spec.rb
Labels: valkyrization, valkyrie-fedora

#6475 Marks test suite as ActiveFedora-only, since indexer is only used with AF objects.
  spec/indexers/hyrax/collection_indexer_spec.rb
Labels: valkyrization, notes-valkyrie

#6476 Adds switches between AF and Valkyrie expected classes.
  spec/search_builders/hyrax/my/collections_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6477 Marks test suite as ActiveFedora-only, since writer relies on AF methods.
  spec/lib/hyrax/resource_sync/change_list_writer_spec.rb
Labels: valkyrization, notes-valkyrie

#6478 Enqueues Job that wasn't calling.
  spec/controllers/hyrax/file_sets_controller_spec.rb
Labels: valkyrization, notes-valkyrie

#6480 Utilizes Valkyrie patterns for edit_work_spec.
  spec/features/edit_work_spec.rb
Labels: valkyrization, notes-valkyrie

#6483 Adapt citations controller spec for valkyrie resources
  spec/controllers/hyrax/citations_controller_spec.rb
Labels: notes-valkyrie, notes-tests
