Repository samvera/hyrax, pull requests merged in 2023-06, with the labels that each got.

#6094 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: notes-docs

#6097 Disable analytics dashboard for GA4 until support is done
  app/controllers/hyrax/admin/analytics/collection_reports_controller.rb
  app/controllers/hyrax/admin/analytics/work_reports_controller.rb
  app/views/hyrax/admin/analytics/collection_reports/index.html.erb
  app/views/hyrax/admin/analytics/work_reports/index.html.erb
  app/views/hyrax/base/_show_actions.html.erb
  app/views/hyrax/base/_work_button_row.html.erb
  app/views/hyrax/dashboard/_user_activity.html.erb
  app/views/hyrax/dashboard/show_admin.html.erb
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
  app/views/hyrax/file_sets/_show_actions.html.erb
Labels: notes-bugfix

#6101 thumbnails are by id in pg version, not by alternate id
  app/services/hyrax/thumbnail_path_service.rb
Labels: notes-valkyrie

#6103 #5798 Valkyrie: Show all collection descriptive metadata
  .koppie/app/forms/collection_resource_form.rb
  .koppie/app/indexers/collection_resource_indexer.rb
  .koppie/app/models/collection_resource.rb
  .koppie/config/metadata/collection_resource.yaml
  app/indexers/hyrax/pcdm_collection_indexer.rb
  spec/jobs/valkyrie_ingest_job_spec.rb
Labels: notes-valkyrie

#6102 Give IIIF Manifests Some Wings
  .dassie/config/initializers/riiif.rb
  .koppie/config/initializers/riiif.rb
  app/indexers/hyrax/valkyrie_file_set_indexer.rb
  app/indexers/hyrax/valkyrie_work_indexer.rb
  app/models/concerns/hyrax/solr_document_behavior.rb
  app/presenters/hyrax/iiif_manifest_presenter.rb
  lib/generators/hyrax/templates/config/initializers/riiif.rb
  spec/indexers/hyrax/valkyrie_file_set_indexer_spec.rb
Labels: notes-valkyrie
