Repository samvera/hyrax, pull requests merged in 2024-08, with the labels that each got.

#6867 Fix catalog search dropdown
  app/assets/javascripts/hyrax/search.js
  app/views/catalog/_search_form.html.erb
Labels: notes-bugfix

#6853 Explicitly cast metrics from Matomo to be integers
  app/services/hyrax/analytics/matomo.rb
Labels: notes-bugfix

#6845 Testing review
  .github/release.yml
  app/assets/stylesheets/hyrax/_forms.scss
Labels: notes-accessibility

#6865 Use faster solr faceting for dashboard stats
  app/models/hyrax/statistic.rb
Labels: notes-minor

#6886 fix ga4 stats not being able to retrieve events properly, add work show to user vitals
  app/assets/javascripts/hyrax/analytics_events.js
  app/services/hyrax/analytics/ga4.rb
  app/services/hyrax/analytics/ga4/base.rb
  app/services/hyrax/analytics/ga4/events.rb
  app/services/hyrax/analytics/ga4/events_daily.rb
  app/services/hyrax/analytics/ga4/visits.rb
  app/services/hyrax/analytics/ga4/visits_daily.rb
  app/views/hyrax/users/_vitals.html.erb
  config/locales/hyrax.en.yml
Labels: notes-bugfix

#6889 allow base64 encoding of ga4 user env, fix user stat collection nil bug
  app/services/hyrax/analytics/ga4.rb
  app/services/hyrax/user_stat_importer.rb
Labels: notes-bugfix

#6893 Fix subtle background gradient on featured works
  app/assets/stylesheets/hyrax/_nestable.scss
Labels: notes-bugfix
