Repository samvera/hyrax, pull requests merged in 2024-10, with the labels that each got.

#6919 Include valkyrie in :clean_repo
  spec/spec_helper.rb
Labels: notes-tests

#6914 Lazy migrate characterization along with file
  app/jobs/migrate_files_to_valkyrie_job.rb
  lib/freyja/persister.rb
  lib/goddess/query.rb
  lib/wings/setup.rb
  spec/jobs/migrate_files_to_valkyrie_job_spec.rb
  spec/lib/freyja/persister_spec.rb
  spec/spec_helper.rb
Labels: notes-bugfix

#6922 Fixes Wings migration of based_near attribute in to_resource
  lib/wings/transformer_value_mapper.rb
  spec/wings/attribute_transformer_spec.rb
Labels: notes-bugfix

#6927 Fix location indexing
  app/indexers/concerns/hyrax/location_indexer.rb
Labels: notes-bugfix

#6928 Fix index field name typo
  app/indexers/concerns/hyrax/location_indexer.rb
Labels: notes-bugfix

#6931 Implement chunky uploads
  app/assets/javascripts/hyrax/uploader.js
  app/controllers/hyrax/uploads_controller.rb
  app/views/hyrax/uploads/create.json.jbuilder
  spec/controllers/hyrax/uploads_controller_spec.rb
  spec/fixtures/different_file.png
Labels: notes-minor

#6933 Adding alt attribute for collection thumbnail
  app/views/catalog/_thumbnail_list_collection.html.erb
  app/views/catalog/_thumbnail_list_default.html.erb
Labels: notes-accessibility

#6934 darker link color for contrast
  app/forms/hyrax/forms/admin/appearance.rb
Labels: notes-accessibility

#6937 call to_rdf_representation in #collections?
  app/models/hyrax/collection_type.rb
Labels: notes-minor
