Repository samvera/hyrax, pull requests merged in 2024-01, with the labels that each got.

#6549 Moves test that checks AF objects with Valkyrie Ids, then Valkyries it at `spec/services/hyrax/custom_queries/navigators/child_file_sets_navigator_spec.rb`.
  spec/services/hyrax/custom_queries/navigators/child_file_sets_navigator_spec.rb
  spec/wings/services/custom_queries/navigators/child_file_sets_navigator_spec.rb
Labels: valkyrization, notes-valkyrie

#6523 Alters objects and tests to play well in Koppie for spec/services/hyrax/admin_set_create_service_spec.rb.
  spec/services/hyrax/admin_set_create_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6550 Valkyrization: Fix failing tests in `by_depositor_spec.rb`
  spec/services/hyrax/statistics/works/by_depositor_spec.rb
Labels: valkyrization, notes-valkyrie

#6551 Moves test that checks AF objects with Valkyrie Ids, then Valkyries it at `spec/services/hyrax/custom_queries/navigators/child_collections_navigator_spec.rb`.
  spec/services/hyrax/custom_queries/navigators/child_collections_navigator_spec.rb
  spec/wings/services/custom_queries/navigators/child_collections_navigator_spec.rb
Labels: valkyrization, notes-valkyrie

#6552 Valkyrizes `spec/services/hyrax/statistics/file_sets/by_format_spec.rb`.
  spec/services/hyrax/statistics/file_sets/by_format_spec.rb
Labels: valkyrization, notes-valkyrie

#6570 Update Gemfile for bundler 2.5
  Gemfile
Labels: notes-bugfix

#6553 Valkyrizes `spec/services/hyrax/file_set_csv_service_spec.rb`.
  config/metadata/core_metadata.yaml
  config/metadata/file_set_metadata.yaml
  spec/services/hyrax/file_set_csv_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6554 Marks `spec/services/hyrax/graph_exporter_spec.rb` as ActiveFedora-only.
  spec/services/hyrax/graph_exporter_spec.rb
Labels: valkyrization, notes-valkyrie

#6555 Valkyrizes `spec/services/hyrax/characterization/valkyrie_characterization_service_spec.rb`.
  spec/services/hyrax/characterization/valkyrie_characterization_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6556 Adds work class swapping to `spec/services/hyrax/workflow/changes_required_notification_spec.rb`.
  spec/services/hyrax/workflow/changes_required_notification_spec.rb
Labels: valkyrization, notes-valkyrie

#6558 Allows for multiple Deprecation calls.
  spec/services/hyrax/change_content_depositor_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6560 Fixes enumerator comparisons and refactors.
  spec/services/hyrax/collections/collection_member_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6562 Valkyrizes `spec/views/hyrax/homepage/_sortable_featured.html.erb_spec.rb`.
  spec/views/hyrax/homepage/_sortable_featured.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6564 Requeries collection and admin_set objects in `spec/services/hyrax/collections/permissions_create_service_spec.rb`.
  spec/services/hyrax/collections/permissions_create_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6565 Updates FileMetadata objects across environments for `spec/models/hyrax/file_metadata_spec.rb`.
  spec/models/hyrax/file_metadata_spec.rb
Labels: valkyrization, notes-valkyrie

#6566 Marks ActiveFedora tests in `spec/jobs/import_url_job_spec.rb`.
  spec/jobs/import_url_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6563 Marks ActiveFedora tests in `spec/services/hyrax/workflow/workflow_factory_spec.rb`.
  spec/services/hyrax/workflow/workflow_factory_spec.rb
Labels: valkyrization, notes-valkyrie

#6568 Marks ActiveFedora tests in `spec/jobs/content_restored_version_event_job_spec.rb`.
  spec/jobs/content_restored_version_event_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6569 Marks ActiveFedora tests in `spec/models/concerns/hyrax/collection_behavior_spec.rb`.
  spec/models/concerns/hyrax/collection_behavior_spec.rb
Labels: valkyrization, notes-valkyrie

#6561 Valkyrizes `spec/models/sipity/entity_spec.rb`.
  spec/models/sipity/entity_spec.rb
Labels: valkyrization, notes-valkyrie

#6567 Converts enumerators into arrays for `spec/services/hyrax/collections/nested_collection_persistence_service_spec.rb`.
  spec/services/hyrax/collections/nested_collection_persistence_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6557 Marks `spec/services/hyrax/statistics/collections/over_time_spec.rb` as ActiveFedora-only.
  spec/services/hyrax/statistics/collections/over_time_spec.rb
Labels: valkyrization, notes-valkyrie

#6571 Marks ActiveFedora tests in `spec/services/hyrax/find_objects_via_solr_service_spec.rb`.
  spec/services/hyrax/find_objects_via_solr_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6572 Marks ActiveFedora tests in `spec/indexers/hyrax/deep_indexing_service_spec.rb`.
  spec/indexers/hyrax/deep_indexing_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6573 Marks ActiveFedora tests in `spec/indexers/hyrax/file_set_indexer_spec.rb`.
  spec/indexers/hyrax/file_set_indexer_spec.rb
Labels: valkyrization, notes-valkyrie

#6574 Valkyrizes `spec/services/hyrax/collections/collection_member_search_service_spec.rb`.
  spec/services/hyrax/collections/collection_member_search_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6575 Fixes `spec/services/hyrax/workflow/grant_edit_to_depositor_spec.rb` for dassie-valkyrie-test.
  spec/services/hyrax/workflow/grant_edit_to_depositor_spec.rb
Labels: valkyrization, notes-valkyrie

#6576 Valkyrizes `spec/views/hyrax/file_sets/_permission_form.html.erb_spec.rb`.
  spec/views/hyrax/file_sets/_permission_form.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6577 Valkyrizes `spec/views/hyrax/file_sets/_permission.html.erb_spec.rb`.
  spec/views/hyrax/file_sets/_permission.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6579 Valkyrization: Fix failing tests in `deposited_notification_spec.rb`
  spec/services/hyrax/workflow/deposited_notification_spec.rb
Labels: valkyrization, notes-valkyrie

#6580 Fixes failing test in `spec/views/hyrax/file_sets/media_display/_video.html.erb_spec.rb`.
  app/views/hyrax/file_sets/media_display/_video.html.erb
Labels: valkyrization, notes-valkyrie

#6581 Fixes failing test in `spec/views/hyrax/file_sets/media_display/_audio.html.erb_spec.rb`.
  app/views/hyrax/file_sets/media_display/_audio.html.erb
Labels: valkyrization, notes-valkyrie

#6582 Makes application_name dynamically tested in `spec/views/hyrax/users/index.html.erb_spec.rb`.
  spec/views/hyrax/users/index.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6526 Valkyrization: Edit edit_file_spec.rb
  spec/features/edit_file_spec.rb
Labels: valkyrization, notes-valkyrie

#6585 Marks `spec/search_builders/hyrax/work_relation_spec.rb` as ActiveFedora-only.
  spec/search_builders/hyrax/work_relation_spec.rb
Labels: valkyrization, notes-valkyrie

#6584 Marks ActiveFedora tests in `spec/features/work_show_spec.rb`.
  spec/features/work_show_spec.rb
Labels: valkyrization, notes-valkyrie

#6586 Valkyrizes `spec/search_builders/hyrax/dashboard/collections_search_builder_spec.rb`.
  spec/search_builders/hyrax/dashboard/collections_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6587 Valkyrization: Fix failing tests in `transfers_presenter_spec.rb`
  spec/presenters/hyrax/transfers_presenter_spec.rb
Labels: valkyrization, notes-valkyrie

#6588 Marks `spec/jobs/attach_files_to_work_with_ordered_members_job_spec.rb` as ActiveFedora-only.
  spec/jobs/attach_files_to_work_with_ordered_members_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6589 Accounts for Koppie-specific behavior in `spec/features/create_collection_spec.rb`.
  spec/features/create_collection_spec.rb
Labels: valkyrization, notes-valkyrie

#6590 Marks `spec/services/hyrax/visibility_intention_applicator_spec.rb` as ActiveFedora-only.
  spec/services/hyrax/visibility_intention_applicator_spec.rb
Labels: valkyrization, notes-valkyrie

#6591 Makes `spec/services/hyrax/valkyrie_upload_spec.rb` friendly for both Koppie and Dassie.
  spec/services/hyrax/valkyrie_upload_spec.rb
Labels: valkyrization, notes-valkyrie

#6592 Marks ActiveFedora tests in `spec/presenters/hyrax/model_proxy_spec.rb`.
  spec/presenters/hyrax/model_proxy_spec.rb
Labels: valkyrization, notes-valkyrie

#6594 Valkyrization: Mark `persist_directly_contained_output_file_service_spec.rb` as ActiveFedora only
  spec/services/hyrax/persist_directly_contained_output_file_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6595 Marks `spec/services/hyrax/repository_fixity_check_service_spec.rb` as ActiveFedora-only.
  spec/services/hyrax/repository_fixity_check_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6596 Addresses `spec/jobs/lease_expiry_job_spec.rb` and associated factories.
  spec/factories/hyrax_file_set.rb
  spec/factories/hyrax_work.rb
  spec/jobs/lease_expiry_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6598 Valkyrizes `spec/features/dashboard/my_works_spec.rb`.
  spec/features/dashboard/my_works_spec.rb
Labels: valkyrization, notes-valkyrie

#6597 Marks `spec/models/concerns/hyrax/solr_document/ordered_members_spec.rb` as ActiveFedora-only.
  spec/models/concerns/hyrax/solr_document/ordered_members_spec.rb
Labels: valkyrization, notes-valkyrie

#6599 Valkyrization: Mark `work_query_service_spec.rb` as ActiveFedora only
  spec/services/hyrax/work_query_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6600 Valkyrization: Mark `move_all_works_to_admin_set_spec.rb` as ActiveFedora only
  spec/lib/hyrax/move_all_works_to_admin_set_spec.rb
Labels: valkyrization, notes-valkyrie

#6601 Valkyrization: Fix failing tests in `spec/models/sipity_spec.rb`
  spec/models/sipity_spec.rb
Labels: valkyrization, notes-valkyrie

#6602 Valkyrizes `spec/features/iiif_manifest_spec.rb`.
  spec/features/iiif_manifest_spec.rb
Labels: valkyrization, notes-valkyrie

#6603 Accounts for Koppie's config in `spec/models/flipflop_spec.rb`.
  spec/models/flipflop_spec.rb
Labels: valkyrization, notes-valkyrie

#6604 Valkyrizes `spec/services/hyrax/embargo_service_spec.rb`.
  spec/services/hyrax/embargo_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6605 Valkyrization: Fix failing tests in `spec/features/create_work_admin_spec.rb`
  spec/features/create_work_admin_spec.rb
Labels: valkyrization, notes-valkyrie

#6606 Valkyrization: Fix failing tests in `iiif_manifest_cache_prewarm_job_spec.rb`
  spec/jobs/iiif_manifest_cache_prewarm_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6607 Marks `spec/presenters/hyrax/member_presenter_factory_spec.rb` as ActiveFedora-only.
  spec/presenters/hyrax/member_presenter_factory_spec.rb
Labels: valkyrization, notes-valkyrie

#6608 Corrects `spec/search_builders/hyrax/my/collections_search_builder_spec.rb` after environment behaviors alignment.
  spec/search_builders/hyrax/my/collections_search_builder_spec.rb
Labels: valkyrization, notes-valkyrie

#6609 Adds switch for expected solr cor in `spec/valkyrie/indexing/solr/indexing_adapter_spec.rb`.
  spec/valkyrie/indexing/solr/indexing_adapter_spec.rb
Labels: valkyrization, notes-valkyrie

#6610 Marks `spec/forms/hyrax/forms/batch_edit_form_spec.rb` as ActiveFedora-only.
  spec/forms/hyrax/forms/batch_edit_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6614 Accounts for Valkyrie's schema parsing dates differently in `spec/hyrax/schema_spec.rb`.
  spec/hyrax/schema_spec.rb
Labels: valkyrization, notes-valkyrie

#6613 Valkyrizes `spec/views/hyrax/batch_edits/edit.html.erb_spec.rb`.
  spec/views/hyrax/batch_edits/edit.html.erb_spec.rb
Labels: valkyrization, notes-valkyrie

#6612 Converts collection in `spec/features/collection_type_spec.rb` and highlights bug.
  spec/features/collection_type_spec.rb
Labels: valkyrization, notes-valkyrie

#6618 Swaps to :pcdm_collection in `spec/forms/hyrax/forms/admin/collection_type_form_spec.rb`.
  spec/forms/hyrax/forms/admin/collection_type_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6617 Marks `spec/services/hyrax/import_url_failure_service_spec.rb` as ActiveFedora-only.
  spec/services/hyrax/import_url_failure_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6621 Valkyrizes `spec/features/read_only_mode_spec.rb`.
  spec/features/read_only_mode_spec.rb
Labels: valkyrization, notes-valkyrie

#6625 generalize Sipity::Entity() test for solr documents over classes
  spec/models/sipity_spec.rb
Labels: notes-valkyrie, notes-tests

#6626 Marks ActiveFedora test in `spec/models/sipity_spec.rb`.
  spec/models/sipity_spec.rb
Labels: valkyrization, notes-valkyrie

#6628 Adds creator to `spec/features/lease_spec.rb`.
  spec/features/lease_spec.rb
Labels: valkyrization, notes-valkyrie

#6629 Converts collections in `spec/tasks/rake_spec.rb`.
  spec/tasks/rake_spec.rb
Labels: valkyrization, notes-valkyrie

#6631 Changes enum to array in `spec/forms/hyrax/forms/administrative_set_form_spec.rb`.
  spec/forms/hyrax/forms/administrative_set_form_spec.rb
Labels: valkyrization, notes-valkyrie

#6632 Marks `spec/lib/hyrax/resource_sync/resource_list_writer_spec.rb` as ActiveFedora-only.
  spec/lib/hyrax/resource_sync/resource_list_writer_spec.rb
Labels: valkyrization, notes-valkyrie

#6630 Marks ActiveFedora tests in `spec/services/hyrax/workflow/status_list_service_spec.rb`.
  spec/services/hyrax/workflow/status_list_service_spec.rb
Labels: valkyrization, notes-valkyrie

#6633 Valkyrizes `spec/services/hyrax/statistics/works/count_spec.rb`.
  spec/services/hyrax/statistics/works/count_spec.rb
Labels: valkyrization, notes-valkyrie

#6637 Valkyrizes `spec/support/features/batch_edit_actions.rb`.
  spec/features/batch_edit_spec.rb
  spec/support/features/batch_edit_actions.rb
Labels: valkyrization, notes-valkyrie

#6638 Fixes flaky test in `spec/jobs/embargo_expiry_job_spec.rb`.
  spec/jobs/embargo_expiry_job_spec.rb
Labels: valkyrization, notes-valkyrie

#6640 Valkyrization: Fix failing tests in `display_admin_dashboard_spec.rb` for Koppie
  spec/features/dashboard/display_admin_dashboard_spec.rb
Labels: valkyrization, notes-valkyrie

#6641 Valkyrizes `spec/requests/riiif_spec.rb`.
  spec/requests/riiif_spec.rb
Labels: valkyrization, notes-valkyrie

#6639 Valkyrization: Fix failing tests in `spec/valkyrie/indexing/solr/indexing_adapter_spec.rb`
  .koppie/.env
  docker-compose-koppie.yml
  docker-compose-sirenia.yml
  spec/valkyrie/indexing/solr/indexing_adapter_spec.rb
Labels: valkyrization, notes-valkyrie

#6642 Switches object types based on Wings activity in `spec/features/workflow_state_changes_spec.rb`.
  spec/features/workflow_state_changes_spec.rb
Labels: valkyrization, notes-valkyrie

#6643 Allows pending test that passes in CI but fails locally (`spec/services/hyrax/statistics/collections/over_time_spec.rb`).
  spec/services/hyrax/statistics/collections/over_time_spec.rb
Labels: valkyrization, notes-valkyrie

#6646 Add FileMetadata.to_rdf_representation matching recent Resource change
  app/models/hyrax/file_metadata.rb
Labels: notes-valkyrie, notes-bugfix

#6186 ci: add koppie build and test
  .circleci/config.yml
  lib/wings.rb
  spec/spec_helper.rb
Labels: test coverage, notes-valkyrie

#6648 Update Dockerfile to Ruby 3.2.3, Alpine to 3.19
  Dockerfile
Labels: notes-container

#6651 🐛 Favor Hyrax::SolrService where possible
  app/controllers/hyrax/admin/analytics/work_reports_controller.rb
  app/models/hyrax/statistic.rb
  app/services/hyrax/solr_service.rb
  lib/wings/services/custom_queries/find_ids_by_model.rb
Labels: notes-bugfix
