Repository samvera/hyrax, pull requests merged in 2024-06, with the labels that each got.

#6819 Find count by fix
  app/services/hyrax/custom_queries/find_count_by.rb
  lib/freyja/query_service.rb
Labels: notes-bugfix

#6818 Statistics fixes
  app/presenters/hyrax/work_usage.rb
  app/search_builders/hyrax/valkyrie_abstract_type_relation.rb
  app/services/hyrax/solr_service.rb
  app/services/hyrax/statistics/query_service.rb
  app/services/hyrax/statistics/works/over_time.rb
  app/services/hyrax/user_stat_importer.rb
  app/services/hyrax/work_query_service.rb
Labels: notes-valkyrie

#6846 Move clean_repo before hook after :index_adapter
  spec/spec_helper.rb
Labels: notes-tests

#6849 Quiet down CircleCI and have it report as green
  .circleci/config.yml
Labels: notes-tests

#6837 Fix Add Child link
  app/views/hyrax/base/_show_actions.html.erb
Labels: notes-bugfix

#6825 Change default admin set id to `admin_set_default` to avoid issues with encoded slashes
  app/services/hyrax/admin_set_create_service.rb
Labels: notes-bugfix

#6857 Install Alpine's grpc gem and use in test apps
  .dassie/Gemfile
  .koppie/Gemfile
  Dockerfile
  spec/features/work_generator_spec.rb
  spec/services/hyrax/quick_classification_query_spec.rb
Labels: notes-container, notes-tests

#6824 Authentication guard clause in work reports controller
  app/controllers/hyrax/admin/analytics/work_reports_controller.rb
  spec/controllers/hyrax/admin/analytics/work_reports_controller_spec.rb
Labels: notes-bugfix
