Repository samvera/hyrax, pull requests merged in 2024-05, with the labels that each got.

#6806 Set mock response for feature in deposit agreement spec
  spec/features/deposit_agreements_spec.rb
Labels: notes-tests

#6807 Lazy migrate all derivatives
  lib/freyja/resource_factory.rb
Labels: notes-valkyrie

#6815 create google analytics 4 compatibility
  .dassie/Gemfile
  .dassie/config/analytics.yml
  .koppie/Gemfile
  .koppie/config/analytics.yml
  app/assets/javascripts/hyrax/analytics_events.js
  app/controllers/concerns/hyrax/singular_subresource_controller.rb
  app/controllers/hyrax/admin/analytics/work_reports_controller.rb
  app/models/file_download_stat.rb
  app/models/file_view_stat.rb
  app/models/hyrax/statistic.rb
  app/presenters/hyrax/file_usage.rb
  app/presenters/hyrax/stats_usage_presenter.rb
  app/services/hyrax/analytics/ga4.rb
  app/services/hyrax/analytics/ga4/base.rb
  app/services/hyrax/analytics/ga4/events.rb
  app/services/hyrax/analytics/ga4/events_daily.rb
  app/services/hyrax/analytics/ga4/visits.rb
  app/services/hyrax/analytics/ga4/visits_daily.rb
  app/services/hyrax/analytics/google.rb
  app/services/hyrax/analytics/matomo.rb
  app/services/hyrax/analytics/results.rb
  app/views/hyrax/dashboard/show_admin.html.erb
  app/views/layouts/_head_tag_content.html.erb
  app/views/shared/_ga4.html.erb
  hyrax.gemspec
  lib/generators/hyrax/install_generator.rb
  lib/generators/hyrax/templates/config/analytics.yml
  spec/models/file_download_stat_spec.rb
  spec/models/file_view_stat_spec.rb
  spec/models/work_view_stat_spec.rb
Labels: notes-minor
