Repository samvera/hyrax, pull requests merged in 2024-11, with the labels that each got.

#6950 Attempt to fix async flakiness in features/deposit_agreements_spec
  spec/features/deposit_agreements_spec.rb
Labels: notes-tests

#6952 chunk upload bug fix
  app/controllers/hyrax/uploads_controller.rb
  spec/controllers/hyrax/uploads_controller_spec.rb
Labels: notes-minor

#6948 Parameterized lock requests
  app/services/hyrax/lock_manager.rb
  app/services/hyrax/lockable.rb
  spec/services/hyrax/lock_manager_spec.rb
  spec/services/hyrax/lockable_spec.rb
Labels: notes-minor

#6936 Fixing accessibility violations in user detail row
  app/views/hyrax/users/_user_row.html.erb
Labels: notes-accessibility

#6943 Add presentation role to pages form
  app/views/hyrax/pages/_form.html.erb
Labels: notes-accessibility

#6944 Underline link text
  app/assets/stylesheets/_bootstrap-default-overrides.scss
Labels: notes-accessibility

#6945 Fixing missing label violations in the edit collection sharing tab
  app/views/hyrax/dashboard/collections/_form_share.html.erb
Labels: notes-accessibility

#6949 Add overflow to scss
  app/assets/stylesheets/hyrax/_forms.scss
Labels: notes-accessibility

#6951 move span inside button
  app/views/hyrax/file_sets/_permission_form.html.erb
Labels: notes-accessibility

#6953 a11y: Increase size of action menu items
  app/assets/stylesheets/hyrax/_work-show.scss
Labels: notes-accessibility

#6954 Reindex fileset after file lazy migration
  app/jobs/migrate_files_to_valkyrie_job.rb
  spec/jobs/migrate_files_to_valkyrie_job_spec.rb
Labels: notes-bugfix

#6957 Chunk upload follow up 2
  app/controllers/hyrax/uploads_controller.rb
Labels: notes-bugfix

#6969 Add labels to checkbox lists
  app/views/hyrax/leases/_list_expired_active_leases.html.erb
Labels: notes-accessibility

#6965 Adding required data cells to collection membership rows in batch create
  app/views/hyrax/base/_form_member_of_collections.html.erb
Labels: notes-accessibility

#6966 Add id and missing style on disabled checkbox
  app/views/hyrax/dashboard/collections/_list_collections.html.erb
  app/views/hyrax/my/collections/_list_collections.html.erb
Labels: notes-accessibility

#6972 Use TimeService when determining expired embargoes/leases
  app/search_builders/hyrax/expired_embargo_search_builder.rb
  app/search_builders/hyrax/expired_lease_search_builder.rb
Labels: notes-minor

#6930 Always save nonpersisted ACLs
  app/services/hyrax/access_control_list.rb
  app/services/hyrax/custom_queries/find_access_control.rb
  spec/services/hyrax/access_control_list_spec.rb
  spec/services/hyrax/custom_queries/find_access_control_spec.rb
  spec/services/hyrax/listeners/file_metadata_listener_spec.rb
  spec/wings/services/custom_queries/find_access_control_spec.rb
Labels: notes-bugfix

#6973 move valkyrie resource migration code from hyku to hyrax
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/forms/hyrax/forms/pcdm_collection_form.rb
  app/jobs/migrate_resources_job.rb
  app/jobs/valkyrie_create_derivatives_job.rb
  app/models/admin_set.rb
  app/models/hyrax/resource.rb
  app/services/migrate_resource_service.rb
  lib/freyja/persister.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
  spec/jobs/migrate_resources_job_spec.rb
Labels: notes-minor, notes-valkyrie

#6975 Send string ids into job
  lib/freyja/persister.rb
  lib/hyrax/specs/shared_specs/factories/hyrax_work.rb
Labels: notes-bugfix
