Repository samvera/hyrax, pull requests merged in 2024-02, with the labels that each got.

#6647 ♻️ Leverage more of Blacklight's Solr URL
  lib/valkyrie/indexing/solr/indexing_adapter.rb
Labels: notes-minor

#6652 Change embargo/lease ID types to fix nil values being converted to blank strings
  app/models/hyrax/resource.rb
Labels: notes-valkyrie, notes-bugfix

#6667 Rescue exception when collection is missing
  app/helpers/hyrax/hyrax_helper_behavior.rb
  spec/helpers/hyrax_helper_spec.rb
Labels: notes-bugfix

#6688 ✂ Remove useless test
  spec/controllers/hyrax/homepage_controller_spec.rb
Labels: notes-tests

#6686 🧹 Expose Hyrax.config.use_valkyrie=
  lib/hyrax/configuration.rb
  spec/lib/hyrax/configuration_spec.rb
Labels: notes-minor

#6706 🐛 Favor fault tolerant comparison
  app/models/hyrax/resource.rb
Labels: notes-bugfix

#6711 🎁 Publish membership update event
  lib/hyrax/transactions/steps/add_to_parent.rb
  lib/hyrax/transactions/steps/update_work_members.rb
Labels: notes-minor

#6712 🐛 Account for String and Valkyrie::ID Permissions
  app/models/concerns/hyrax/ability.rb
  app/models/concerns/hyrax/ability/collection_ability.rb
Labels: notes-bugfix

#6715 Set valkyrie models as default in Hyrax.config
  .dassie/config/initializers/hyrax.rb
  lib/hyrax/configuration.rb
Labels: notes-major

#6718 The helm chart says it evaluates extraEnvVars but it was not actually doing so
  chart/hyrax/templates/_tmplvalues.tpl
  chart/hyrax/templates/deployment-worker.yaml
  chart/hyrax/templates/deployment.yaml
Labels: notes-container

#6727 New query strategy to join FileSet solr documents
  app/search_builders/hyrax/catalog_search_builder.rb
  spec/controllers/catalog_controller_spec.rb
  spec/search_builders/hyrax/catalog_search_builder_spec.rb
Labels: notes-bugfix
