Repository samvera/hyrax, pull requests merged in 2024-03, with the labels that each got.

#6726 Prevent unauthenticated access to /dashboard/collections/
  app/controllers/hyrax/dashboard/collections_controller.rb
  spec/controllers/hyrax/dashboard/collections_controller_spec.rb
Labels: notes-bugfix

#6728 Application generation fixes
  documentation/developing-your-hyrax-based-app.md
  lib/generators/hyrax/templates/config/initializers/hyrax.rb
Labels: notes-bugfix, notes-docs

#6748 use `find_files(file_set: file_set)` in various specs
  spec/controllers/hyrax/file_sets_controller_spec.rb
  spec/hyrax/transactions/file_set_destroy_spec.rb
  spec/hyrax/transactions/work_destroy_spec.rb
  spec/presenters/hyrax/version_list_presenter_spec.rb
Labels: notes-tests

#6753 make `default_workflow_spec.rb` order independent
  spec/features/default_workflow_spec.rb
Labels: notes-tests

#6735 fix blueimp file upload progress bars
  app/assets/stylesheets/hyrax/_file_upload.scss
  app/views/hyrax/uploads/_js_templates.html.erb
  app/views/hyrax/uploads/_js_templates_branding.html.erb
  app/views/hyrax/uploads/_js_templates_versioning.html.erb
Labels: notes-bugfix
