Repository samvera/hyrax, pull requests merged in 2025-04, with the labels that each got.

#7053 Queueable index adapter
  Gemfile
  app/jobs/concerns/hyrax/queued_job_behavior.rb
  app/jobs/hyrax/queued_delete_job.rb
  app/jobs/hyrax/queued_indexing_job.rb
  config/initializers/indexing_adapter_initializer.rb
  docker-compose-dassie.yml
  lib/hyrax.rb
  lib/valkyrie/indexing/redis_queue/indexing_adapter.rb
  spec/jobs/concerns/hyrax/queued_job_behavior_spec.rb
  spec/jobs/hyrax/queued_delete_job_spec.rb
  spec/jobs/hyrax/queued_indexing_job_spec.rb
  spec/valkyrie/indexing/redis_queue/indexing_adapter_spec.rb
Labels: notes-minor

#7060 🐛 Creates a fallback for m3 flexible schema
  app/services/hyrax/m3_schema_loader.rb
  spec/services/hyrax/m3_schema_loader_spec.rb
Labels: notes-bugfix

#7061 🐛 Admin Set dropdown label when creating new work
  app/controllers/hyrax/my/works_controller.rb
Labels: notes-bugfix

#7058 Change base image to debian
  Dockerfile
Labels: notes-container

#7056 should fix accessibility issue
  app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
Labels: notes-accessibility

#7072 Prep v5.1.0
  documentation/developing-your-hyrax-based-app.md
  lib/hyrax/version.rb
  template.rb
Labels: notes-docs

#7075 Compile imagemagick on arm64
  Dockerfile
Labels: notes-container
