Repository samvera/hyrax, pull requests merged in 2025-05, with the labels that each got.

#7081 [5.0 forward port] fix file metadata look up for valkyrie objects
  app/controllers/concerns/hyrax/valkyrie_downloads_controller_behavior.rb
  app/models/hyrax/file_metadata.rb
Labels: notes-bugfix

#7083 [5.0 forward port] Add depositor_ssim to core_metadata.yaml
  config/metadata/core_metadata.yaml
Labels: notes-minor

#7084 [5.0 forward port] Google analytics improvements
  app/controllers/hyrax/admin/analytics/work_reports_controller.rb
  app/services/hyrax/analytics/ga4.rb
  app/services/hyrax/analytics/ga4/base.rb
  app/views/hyrax/admin/analytics/collection_reports/_top_collections.html.erb
  app/views/hyrax/admin/analytics/work_reports/_top_file_set_downloads.html.erb
  app/views/hyrax/admin/analytics/work_reports/_top_works.html.erb
  app/views/hyrax/admin/analytics/work_reports/_work_files.html.erb
  lib/hyrax/configuration.rb
  spec/lib/hyrax/analytics_spec.rb
Labels: notes-minor

#7077 Use solr by default in Hyrax::CustomQueries::FindIdsByModel
  app/models/concerns/hyrax/ability.rb
  app/services/hyrax/custom_queries/find_ids_by_model.rb
  lib/wings/valkyrie/query_service.rb
  spec/jobs/create_work_job_spec.rb
  spec/services/hyrax/custom_queries/find_ids_by_model_spec.rb
Labels: notes-minor

#7094 New nurax deployment system
  .github/workflows/lint-build-test.yml
  .github/workflows/main.yml
Labels: notes-tests

#7080 [5.0 forward port] Redis Index Queue
  Gemfile
  app/jobs/concerns/hyrax/queued_job_behavior.rb
  app/jobs/hyrax/queued_delete_job.rb
  app/jobs/hyrax/queued_indexing_job.rb
  config/initializers/indexing_adapter_initializer.rb
  docker-compose-dassie.yml
  lib/hyrax.rb
  lib/valkyrie/indexing/redis_queue/indexing_adapter.rb
  spec/jobs/concerns/hyrax/queued_job_behavior_spec.rb
  spec/jobs/hyrax/queued_delete_job_spec.rb
  spec/jobs/hyrax/queued_indexing_job_spec.rb
  spec/valkyrie/indexing/redis_queue/indexing_adapter_spec.rb
Labels: notes-minor

#7095 Use solr for Ability admin set check
  app/models/concerns/hyrax/ability.rb
  spec/features/create_work_spec.rb
Labels: notes-bugfix

#7107 Add :hide_social_buttons feature flipper
  app/views/hyrax/base/_social_media.html.erb
  config/features.rb
  spec/views/hyrax/base/_social_media.html.erb_spec.rb
Labels: notes-minor

#7110 Restore Rails 6.1 support
  .dassie/Gemfile
  .dassie/config/application.rb
  .dassie/db/schema.rb
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  config/initializers/new_framework_defaults_7_2.rb
  config/initializers/reform_rails_6_1_monkey_patch.rb
  hyrax.gemspec
  lib/hyrax/controlled_vocabulary/importer/language.rb
  spec/spec_helper.rb
  spec/views/hyrax/single_use_links_viewer/show.html.erb_spec.rb
Labels: notes-bugfix

#7115 Use permission manager when granting
  app/jobs/hyrax/propagate_change_depositor_job.rb
  app/services/hyrax/change_depositor_service.rb
  spec/jobs/hyrax/propagate_change_depositor_job_spec.rb
  spec/services/hyrax/change_depositor_service_spec.rb
Labels: notes-bugfix
