Repository samvera/hyrax, pull requests merged in 2025-09, with the labels that each got.

#7173 update to bitnami legacy docker images
  .github/workflows/release-charts.yml
  chart/hyrax/Chart.yaml
  chart/hyrax/values.yaml
  docker-compose-dassie.yml
  docker-compose-koppie.yml
  docker-compose-sirenia.yml
Labels: notes-container

#7178 🐛 Collections facet in catalog search
  app/indexers/hyrax/indexers/pcdm_object_indexer.rb
  spec/indexers/hyrax/indexers/pcdm_object_indexer_spec.rb
Labels: notes-bugfix

#7174 Flexible profile loaders
  .dassie/db/migrate/20240606205215_create_hyrax_flexible_schemas.rb
  .dassie/db/migrate/20240606205216_add_contexts_to_hyrax_flexible_schemas.rb
  .dassie/db/schema.rb
  .gitignore
  .koppie/db/migrate/20240606205215_create_hyrax_flexible_schemas.rb
  .koppie/db/migrate/20240606205216_add_contexts_to_hyrax_flexible_schemas.rb
  .koppie/db/schema.rb
  app/controllers/hyrax/admin/metadata_profiles_controller.rb
  app/models/concerns/hyrax/ability.rb
  app/models/concerns/hyrax/ability/flexible_metadata_ability.rb
  app/models/hyrax/flexible_schema.rb
  app/presenters/hyrax/flexible_schema_presenter_behavior.rb
  app/services/hyrax/m3_schema_loader.rb
  app/services/hyrax/schema_loader.rb
  app/services/hyrax/simple_schema_loader.rb
  app/utils/hyrax/required_data_seeder.rb
  app/utils/hyrax/required_data_seeders/flexible_profile_seeder.rb
  app/views/hyrax/admin/metadata_profiles/_import_modal.html.erb
  app/views/hyrax/admin/metadata_profiles/index.html.erb
  app/views/hyrax/dashboard/sidebar/_metadata.html.erb
  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/metadata_profiles/m3_profile.yaml
  config/routes.rb
  documentation/flexible_metadata.md
  lib/generators/hyrax/templates/db/migrate/20240606205215_create_hyrax_flexible_schemas.rb.erb
  lib/generators/hyrax/templates/db/migrate/20240606205216_add_contexts_to_hyrax_flexible_schemas.rb.erb
  lib/hyrax.rb
  lib/hyrax/configuration.rb
  lib/hyrax/schema.rb
  spec/fixtures/files/m3_profile.yaml
  spec/hyrax/schema_spec.rb
  spec/services/hyrax/m3_schema_loader_spec.rb
  spec/services/hyrax/schema_loader_spec.rb
  spec/services/hyrax/simple_schema_loader_spec.rb
  spec/spec_helper.rb
Labels: notes-minor

#7191 [Forward] Use post method for nested collection queries
  app/services/hyrax/collections/nested_collection_query_service.rb
Labels: notes-bugfix

#7193 Additional flexible metadata fixes for Dassie
  app/actors/hyrax/actors/file_actor.rb
  app/actors/hyrax/actors/file_set_actor.rb
  app/controllers/concerns/hyrax/ensure_migrated_behavior.rb
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/controllers/hyrax/batch_uploads_controller.rb
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/controllers/hyrax/file_sets_controller.rb
  app/forms/hyrax/forms/batch_upload_form.rb
  app/forms/hyrax/forms/resource_batch_edit_form.rb
  app/forms/hyrax/forms/resource_form.rb
  app/jobs/create_work_job.rb
  app/models/concerns/hyrax/collection_behavior.rb
  app/models/hyrax/change_set.rb
  app/models/hyrax/resource.rb
  app/models/job_io_wrapper.rb
  app/services/hyrax/workflow/workflow_factory.rb
  app/uploaders/hyrax/uploaded_file_uploader.rb
  app/utils/hyrax/data_destroyers/collection_branding_destroyer.rb
  config/metadata/batch_edit_metadata.yaml
  lib/hyrax/indexer.rb
  spec/features/batch_create_spec.rb
  spec/forms/hyrax/forms/batch_upload_form_spec.rb
  spec/forms/hyrax/forms/permission_template_form_spec.rb
  spec/models/job_io_wrapper_spec.rb
  spec/views/hyrax/batch_uploads/_form.html.erb_spec.rb
Labels: notes-minor

#7194 Updates to virus scanning system
  .dassie/Gemfile
  .koppie/Gemfile
  Dockerfile
  app/models/hyrax/uploaded_file.rb
  app/models/hyrax/virus_scanner.rb
  bin/dev-entrypoint.sh
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  docker-compose-dassie.yml
  docker-compose-koppie.yml
  docker-compose-sirenia.yml
  spec/models/hyrax/uploaded_file_spec.rb
  spec/models/hyrax/virus_scanner_spec.rb
  spec/spec_helper.rb
Labels: notes-minor, notes-container

#7197 ⚙️ Temporarily disable batch_upload feature
  app/assets/stylesheets/hyrax/_admin_features.scss
  app/assets/stylesheets/hyrax/_hyrax.scss
  app/strategies/hyrax/strategies/disable_feature_strategy.rb
  config/features.rb
  spec/features/batch_edit_spec.rb
Labels: notes-minor

#7203 ⚙️ Adds 5.* branches to auto run pipelines
  .github/workflows/lint-build-test.yml
Labels: notes-container

#7204 Fixes lazy migration form bug (5.0-flexible)
  app/services/migrate_resource_service.rb
Labels: notes-bugfix
